import type {
  BossCharacterDesign,
  BossPresentationTier,
  BossPresentationTierDesign,
  BuddyCosmetics,
} from '../types';
import { getBuddyCharacterDesign } from './buddyCharacters';

type BossDesignSeed = Omit<
  BossCharacterDesign,
  'id' | 'appendageVariantId' | 'presentationTiers'
> & {
  alternateAppendage?: boolean;
};

function createPresentationTiers(
  bossId: string,
): BossPresentationTierDesign[] {
  return [
    {
      id: `${bossId}-presentation-normal`,
      tier: 'normal',
      label: 'Normal',
      poseId: 'boss-entrance',
      equipmentCue: 'Signature equipment secured',
      arenaLightingClass: 'boss-lighting-normal',
      motionCue: 'Measured breathing',
    },
    {
      id: `${bossId}-presentation-pumped`,
      tier: 'pumped',
      label: 'Pumped',
      poseId: 'front-flex',
      equipmentCue: 'Wraps tightened',
      arenaLightingClass: 'boss-lighting-pumped',
      motionCue: 'Confident pump pulse',
    },
    {
      id: `${bossId}-presentation-overload`,
      tier: 'overload',
      label: 'Overload',
      poseId: 'side-pose',
      equipmentCue: 'Overload bands engaged',
      arenaLightingClass: 'boss-lighting-overload',
      motionCue: 'Heavy controlled breathing',
    },
    {
      id: `${bossId}-presentation-final-round`,
      tier: 'final-round',
      label: 'Final Round',
      poseId: 'back-flex',
      equipmentCue: 'Champion crest revealed',
      arenaLightingClass: 'boss-lighting-final',
      motionCue: 'Final stance lock',
    },
    {
      id: `${bossId}-presentation-defeated`,
      tier: 'defeated',
      label: 'Defeated',
      poseId: 'fatigue',
      equipmentCue: 'Equipment lowered safely',
      arenaLightingClass: 'boss-lighting-defeated',
      motionCue: 'Respectful recovery breath',
    },
  ];
}

function bossDesign(seed: BossDesignSeed): BossCharacterDesign {
  const speciesDesign = getBuddyCharacterDesign(seed.speciesId);
  return {
    ...seed,
    id: `boss-character-${seed.bossId}`,
    appendageVariantId:
      speciesDesign.appendageOptions[seed.alternateAppendage ? 1 : 0]?.id ??
      speciesDesign.defaultCosmetics.appendageVariantId,
    presentationTiers: createPresentationTiers(seed.bossId),
  };
}

export const BOSS_CHARACTER_DESIGNS: BossCharacterDesign[] = [
  bossDesign({
    bossId: 'home-watchman',
    speciesId: 'brawny-bear',
    buildLabel: 'Compact mat strongman',
    primaryMuscleEmphasis: 'forearms',
    trainingPhilosophy: 'A safe brace creates room for the next attempt.',
    signaturePoseId: 'victory-grounded',
    signatureClothing: 'Moss wrist wraps with chalk edge stitching',
    signatureEquipment: 'Wide spotter wraps',
    primaryPaletteId: 'bark',
    secondaryPaletteId: 'moss',
    accentPaletteId: 'amber',
    patternId: 'pattern-shoulder-bands',
    bodySizeId: 'compact',
    muscleDefinitionId: 'defined',
    accessoryIds: ['accessory-wraps'],
    rareTraitId: 'rare-none',
    expressionId: 'cheerful',
    battleStance: 'Low square brace with open forearms',
    entranceAnimationId: 'boss-watchman-mat-stomp',
    victoryAnimationId: 'boss-watchman-spot-salute',
  }),
  bossDesign({
    bossId: 'home-librarian',
    speciesId: 'buff-otter',
    buildLabel: 'Lean mobility coach',
    primaryMuscleEmphasis: 'core',
    trainingPhilosophy: 'A clean reset is a technical victory.',
    signaturePoseId: 'victory-spring',
    signatureClothing: 'Tide headband and pale route sash',
    signatureEquipment: 'Cadence tally band',
    primaryPaletteId: 'sand',
    secondaryPaletteId: 'tide',
    accentPaletteId: 'mint',
    patternId: 'pattern-center-stripe',
    bodySizeId: 'standard',
    muscleDefinitionId: 'smooth',
    accessoryIds: ['accessory-headband'],
    rareTraitId: 'rare-none',
    expressionId: 'focused',
    battleStance: 'Long low stance with a curling counter hand',
    entranceAnimationId: 'boss-librarian-ribbon-turn',
    victoryAnimationId: 'boss-librarian-page-flourish',
    alternateAppendage: true,
  }),
  bossDesign({
    bossId: 'a-rhino',
    speciesId: 'ripped-rhino',
    buildLabel: 'Upper-body rail specialist',
    primaryMuscleEmphasis: 'shoulders',
    trainingPhilosophy: 'Press along one honest line and defend it.',
    signaturePoseId: 'victory-flex',
    signatureClothing: 'Coral shoulder bands',
    signatureEquipment: 'Bench marshal grip gloves',
    primaryPaletteId: 'slate',
    secondaryPaletteId: 'iron',
    accentPaletteId: 'coral',
    patternId: 'pattern-shoulder-bands',
    bodySizeId: 'broad',
    muscleDefinitionId: 'etched',
    accessoryIds: ['accessory-gloves'],
    rareTraitId: 'rare-metallic-tip',
    expressionId: 'fierce',
    battleStance: 'Forward horn line over parallel forearms',
    entranceAnimationId: 'boss-rhino-rail-charge',
    victoryAnimationId: 'boss-rhino-horn-raise',
    alternateAppendage: true,
  }),
  bossDesign({
    bossId: 'a-bison',
    speciesId: 'boulder-bison',
    buildLabel: 'Heavy carry anchor',
    primaryMuscleEmphasis: 'back',
    trainingPhilosophy: 'Pressure should rise slowly enough to control.',
    signaturePoseId: 'victory-grounded',
    signatureClothing: 'Redline chain draped below the hump',
    signatureEquipment: 'Measured carry chain',
    primaryPaletteId: 'bark',
    secondaryPaletteId: 'iron',
    accentPaletteId: 'coral',
    patternId: 'pattern-center-stripe',
    bodySizeId: 'standard',
    muscleDefinitionId: 'defined',
    accessoryIds: ['accessory-chain'],
    rareTraitId: 'rare-none',
    expressionId: 'steady',
    battleStance: 'Still horn loop with four planted feet',
    entranceAnimationId: 'boss-bison-chain-set',
    victoryAnimationId: 'boss-bison-redline-bow',
  }),
  bossDesign({
    bossId: 'b-wolf',
    speciesId: 'iron-wolf',
    buildLabel: 'Lean counter specialist',
    primaryMuscleEmphasis: 'back',
    trainingPhilosophy: 'The smallest angle change can reverse a pull.',
    signaturePoseId: 'victory-spring',
    signatureClothing: 'Blue hand tape and split-tail marker',
    signatureEquipment: 'Counter-read gloves',
    primaryPaletteId: 'slate',
    secondaryPaletteId: 'midnight',
    accentPaletteId: 'sky',
    patternId: 'pattern-speckle',
    bodySizeId: 'compact',
    muscleDefinitionId: 'etched',
    accessoryIds: ['accessory-gloves'],
    rareTraitId: 'rare-metallic-tip',
    expressionId: 'focused',
    battleStance: 'Narrow centerline with an offset weighted tail',
    entranceAnimationId: 'boss-wolf-rivet-feint',
    victoryAnimationId: 'boss-wolf-counter-point',
    alternateAppendage: true,
  }),
  bossDesign({
    bossId: 'b-boar',
    speciesId: 'muscled-boar',
    buildLabel: 'Low-set hip-drive powerlifter',
    primaryMuscleEmphasis: 'chest',
    trainingPhilosophy: 'Build tension first; ring the bell once.',
    signaturePoseId: 'victory-flex',
    signatureClothing: 'Copper lifting belt',
    signatureEquipment: 'Kettle-handle tusk guards',
    primaryPaletteId: 'clay',
    secondaryPaletteId: 'bark',
    accentPaletteId: 'amber',
    patternId: 'pattern-none',
    bodySizeId: 'broad',
    muscleDefinitionId: 'smooth',
    accessoryIds: ['accessory-belt'],
    rareTraitId: 'rare-none',
    expressionId: 'playful',
    battleStance: 'Hips low behind guarded tusks',
    entranceAnimationId: 'boss-boar-bell-stamp',
    victoryAnimationId: 'boss-boar-belt-pop',
  }),
  bossDesign({
    bossId: 'h1-gryphon',
    speciesId: 'prismantle',
    buildLabel: 'Angular shoulder technician',
    primaryMuscleEmphasis: 'shoulders',
    trainingPhilosophy: 'Every facet offers a new line of control.',
    signaturePoseId: 'victory-spring',
    signatureClothing: 'Violet fin wraps',
    signatureEquipment: 'Facet-reading prism bands',
    primaryPaletteId: 'violet',
    secondaryPaletteId: 'plum',
    accentPaletteId: 'mint',
    patternId: 'pattern-shoulder-bands',
    bodySizeId: 'standard',
    muscleDefinitionId: 'etched',
    accessoryIds: ['accessory-wraps'],
    rareTraitId: 'rare-glow-lines',
    expressionId: 'focused',
    battleStance: 'Asymmetric fins around a still diamond center',
    entranceAnimationId: 'boss-prism-facet-open',
    victoryAnimationId: 'boss-prism-fold-salute',
    alternateAppendage: true,
  }),
  bossDesign({
    bossId: 'h1-gorilla',
    speciesId: 'manyfold',
    buildLabel: 'Four-arm recovery relay',
    primaryMuscleEmphasis: 'shoulders',
    trainingPhilosophy: 'One arm works while another prepares the reset.',
    signaturePoseId: 'victory-grounded',
    signatureClothing: 'Alternating mint forearm wraps',
    signatureEquipment: 'Four-corner relay bands',
    primaryPaletteId: 'violet',
    secondaryPaletteId: 'iron',
    accentPaletteId: 'mint',
    patternId: 'pattern-speckle',
    bodySizeId: 'compact',
    muscleDefinitionId: 'defined',
    accessoryIds: ['accessory-wraps'],
    rareTraitId: 'rare-none',
    expressionId: 'cheerful',
    battleStance: 'Staggered arms with an open center fold',
    entranceAnimationId: 'boss-manyfold-relay-open',
    victoryAnimationId: 'boss-manyfold-four-salute',
  }),
  bossDesign({
    bossId: 'h2-hydra',
    speciesId: 'vaultwyrm',
    buildLabel: 'Coiled endurance arch',
    primaryMuscleEmphasis: 'core',
    trainingPhilosophy: 'A complete loop distributes every hard pull.',
    signaturePoseId: 'victory-grounded',
    signatureClothing: 'Dark clasp belt',
    signatureEquipment: 'Vault-arc tension ring',
    primaryPaletteId: 'moss',
    secondaryPaletteId: 'iron',
    accentPaletteId: 'glow',
    patternId: 'pattern-center-stripe',
    bodySizeId: 'broad',
    muscleDefinitionId: 'smooth',
    accessoryIds: ['accessory-belt'],
    rareTraitId: 'rare-glow-lines',
    expressionId: 'steady',
    battleStance: 'Closed body loop with a raised crest',
    entranceAnimationId: 'boss-vault-arch-rise',
    victoryAnimationId: 'boss-vault-clasp-close',
    alternateAppendage: true,
  }),
  bossDesign({
    bossId: 'h2-manticore',
    speciesId: 'crownquill',
    buildLabel: 'Crowned foreleg power athlete',
    primaryMuscleEmphasis: 'chest',
    trainingPhilosophy: 'Honor the setup before claiming the drive.',
    signaturePoseId: 'victory-flex',
    signatureClothing: 'Gold crown chain',
    signatureEquipment: 'Summit-drive foreleg cuffs',
    primaryPaletteId: 'coral',
    secondaryPaletteId: 'plum',
    accentPaletteId: 'amber',
    patternId: 'pattern-shoulder-bands',
    bodySizeId: 'standard',
    muscleDefinitionId: 'etched',
    accessoryIds: ['accessory-chain'],
    rareTraitId: 'rare-metallic-tip',
    expressionId: 'fierce',
    battleStance: 'High radial crown over two loaded forelegs',
    entranceAnimationId: 'boss-crown-fan-open',
    victoryAnimationId: 'boss-crown-honor-bow',
  }),
  bossDesign({
    bossId: 'h3-pegasus',
    speciesId: 'manyfold',
    buildLabel: 'Long-line four-arm summit mover',
    primaryMuscleEmphasis: 'shoulders',
    trainingPhilosophy: 'Balance appears when every limb accepts a role.',
    signaturePoseId: 'victory-spring',
    signatureClothing: 'Chalk and gold alternating wraps',
    signatureEquipment: 'Summit relay ribbons',
    primaryPaletteId: 'chalk',
    secondaryPaletteId: 'violet',
    accentPaletteId: 'amber',
    patternId: 'pattern-center-stripe',
    bodySizeId: 'standard',
    muscleDefinitionId: 'etched',
    accessoryIds: ['accessory-wraps', 'accessory-headband'],
    rareTraitId: 'rare-star-mark',
    expressionId: 'cheerful',
    battleStance: 'Two arms high, two low, center fold open',
    entranceAnimationId: 'boss-manyfold-summit-fan',
    victoryAnimationId: 'boss-manyfold-star-fold',
    alternateAppendage: true,
  }),
  bossDesign({
    bossId: 'h3-pegas',
    speciesId: 'prismantle',
    buildLabel: 'Compact prism control master',
    primaryMuscleEmphasis: 'shoulders',
    trainingPhilosophy: 'Precision is strength with nothing wasted.',
    signaturePoseId: 'victory-grounded',
    signatureClothing: 'Gold-edged violet fin sleeves',
    signatureEquipment: 'Zenith line compass',
    primaryPaletteId: 'violet',
    secondaryPaletteId: 'chalk',
    accentPaletteId: 'amber',
    patternId: 'pattern-speckle',
    bodySizeId: 'compact',
    muscleDefinitionId: 'etched',
    accessoryIds: ['accessory-belt'],
    rareTraitId: 'rare-star-mark',
    expressionId: 'focused',
    battleStance: 'Compressed fins around a bright center point',
    entranceAnimationId: 'boss-prism-zenith-flash',
    victoryAnimationId: 'boss-prism-compass-close',
  }),
];

export const BOSS_CHARACTER_DESIGN_BY_BOSS_ID = new Map(
  BOSS_CHARACTER_DESIGNS.map((entry) => [entry.bossId, entry]),
);

export function getBossCharacterDesign(bossId?: string) {
  return bossId ? BOSS_CHARACTER_DESIGN_BY_BOSS_ID.get(bossId) ?? null : null;
}

export function bossBuddyCosmetics(
  design: BossCharacterDesign,
  tier: BossPresentationTier = 'normal',
): BuddyCosmetics {
  const speciesDesign = getBuddyCharacterDesign(design.speciesId);
  const basePreset =
    speciesDesign.physiquePresets.find((entry) =>
      entry.id.endsWith('-physique-specialized'),
    ) ?? speciesDesign.physiquePresets[1]!;
  const base: BuddyCosmetics = {
    version: 2,
    primaryPaletteId: design.primaryPaletteId,
    secondaryPaletteId: design.secondaryPaletteId,
    accentPaletteId: design.accentPaletteId,
    patternId: design.patternId,
    muscleDefinitionId: design.muscleDefinitionId,
    bodySizeId: design.bodySizeId,
    appendageVariantId: design.appendageVariantId,
    accessoryIds: [...design.accessoryIds],
    rareTraitId: design.rareTraitId,
    expressionId: design.expressionId,
    victoryPoseId: design.signaturePoseId,
    entranceAnimationId: design.entranceAnimationId,
    physiquePresetId: basePreset.id,
    physique: {
      ...basePreset.physique,
      postureId: 'proud',
      stanceId: 'planted',
    },
  };
  const primaryField = {
    shoulders: 'shoulderEmphasisId',
    chest: 'chestEmphasisId',
    back: 'backEmphasisId',
    core: 'coreEmphasisId',
    forearms: 'armEmphasisId',
    legs: 'legEmphasisId',
  } as const;
  if (tier === 'normal') return base;
  if (tier === 'pumped') {
    return {
      ...base,
      muscleDefinitionId: 'etched',
      physique: {
        ...base.physique,
        [primaryField[design.primaryMuscleEmphasis]]: 'pronounced',
        pumpEffectId: 'full',
      },
    };
  }
  if (tier === 'overload') {
    return {
      ...base,
      patternId: 'pattern-strength-lines',
      muscleDefinitionId: 'etched',
      accessoryIds: [
        ...base.accessoryIds.filter((id) => id !== 'accessory-none'),
        'accessory-elbow-sleeves',
      ],
      physique: {
        ...base.physique,
        [primaryField[design.primaryMuscleEmphasis]]: 'pronounced',
        overallMassId: 'heavy-mass',
        pumpEffectId: 'full',
        postureId: 'towering',
      },
    };
  }
  if (tier === 'final-round') {
    return {
      ...base,
      patternId: 'pattern-strength-lines',
      muscleDefinitionId: 'etched',
      accessoryIds: [
        ...base.accessoryIds.filter((id) => id !== 'accessory-none'),
        'accessory-victory-medal',
      ],
      rareTraitId: 'rare-glow-lines',
      physique: {
        ...base.physique,
        [primaryField[design.primaryMuscleEmphasis]]: 'pronounced',
        symmetryId: 'stage',
        pumpEffectId: 'full',
        postureId: 'proud',
      },
    };
  }
  return {
    ...base,
    expressionId: 'sleepy',
    rareTraitId: 'rare-none',
    physique: {
      ...base.physique,
      pumpEffectId: 'none',
      postureId: 'coiled',
      stanceId: 'narrow',
    },
  };
}
