import type {
  BuddyAnimationReferences,
  BuddySpecies,
  StarterBuddyDefinition,
} from '../types';

function animationReferences(speciesId: string): BuddyAnimationReferences {
  const prefix = `buddy.${speciesId}`;
  return {
    idle: `${prefix}.idle`,
    walk: `${prefix}.walk`,
    battle: `${prefix}.battle`,
    hurt: `${prefix}.hurt`,
    victory: `${prefix}.victory`,
    signature: `${prefix}.signature`,
  };
}

export const BUDDY_SPECIES: BuddySpecies[] = [
  {
    id: 'brawny-bear',
    dex: 1,
    name: 'Bramblift',
    primaryDiscipline: 'power',
    secondaryDiscipline: 'recovery',
    visualConcept: 'A compact woodland lifter with mossy wrist wraps and a shoulder-wide back.',
    silhouette: 'Round ears, a low square torso, and forearms wider than its feet.',
    personality: 'Protective, jovial, and the first to help reset a training station.',
    habitat: 'Home Gym gardens and the shaded edges of Warm Up Path.',
    gameplayRole: 'A forgiving front-line anchor that pairs force with dependable recovery.',
    baseHp: 48,
    power: 26,
    control: 48,
    stamina: 58,
    form: 13,
    mobility: 8,
    volume: 9,
    growthProfile: {
      id: 'growth-bramblift',
      curve: 'early-surge',
      emphasizedStats: ['baseHp', 'power', 'volume'],
      description: 'Builds useful HP and pressure quickly, then settles into steady gains.',
    },
    captureDifficulty: 1,
    passiveAbility: {
      id: 'passive-bramble-brace',
      name: 'Bramble Brace',
      description: 'Keeps its composure after a hard opposing push and favors stable resets.',
    },
    signatureMove: {
      id: 'move-rooted-press',
      name: 'Rooted Press',
      discipline: 'power',
      description: 'Plants both feet, absorbs the opening pull, then drives through center.',
    },
    animations: animationReferences('brawny-bear'),
    flavor: 'Its moss-wraps tighten only when a training partner signals they are ready.',
    isExotic: false,
    sprite: [
      'MM....MM',
      'MMM..MMM',
      '.MMEEMM.',
      'MMDDDDMM',
      'MMDDDDMM',
      '.MDDDDM.',
      '.MM..MM.',
      'MM....MM',
    ],
    palette: { skin: '#c6945b', core: '#4f6f3f', detail: '#f1d08a', accent: '#273f35' },
  },
  {
    id: 'titan-tortoise',
    dex: 2,
    name: 'Plastrong',
    primaryDiscipline: 'endurance',
    secondaryDiscipline: 'technique',
    visualConcept: 'A mat-patterned shelled Buddy whose plated back resembles interlocking grips.',
    silhouette: 'A broad oval shell, tiny head, and four evenly spaced block feet.',
    personality: 'Patient, exacting, and pleased by routines completed at an even pace.',
    habitat: 'Starter Gym A courtyards and the quiet lanes of Warm Up Path.',
    gameplayRole: 'A late-round stabilizer with high stamina and unusually precise bracing.',
    baseHp: 55,
    power: 22,
    control: 70,
    stamina: 82,
    form: 18,
    mobility: 7,
    volume: 8,
    growthProfile: {
      id: 'growth-plastrong',
      curve: 'steady',
      emphasizedStats: ['baseHp', 'control', 'stamina'],
      description: 'Adds defensive value at a consistent rate without a weak level band.',
    },
    captureDifficulty: 1,
    passiveAbility: {
      id: 'passive-measured-shell',
      name: 'Measured Shell',
      description: 'Rewards sustained control by resisting late-round drift.',
    },
    signatureMove: {
      id: 'move-eight-count-lock',
      name: 'Eight-Count Lock',
      discipline: 'technique',
      description: 'Sets each joint in sequence before applying an unhurried finishing turn.',
    },
    animations: animationReferences('titan-tortoise'),
    flavor: 'The rings on its shell record completed practice sets, never victories over others.',
    isExotic: false,
    sprite: [
      '...MM...',
      '..MDDM..',
      '.MEEEEEM',
      'MMEDDEMM',
      'MMEDDEMM',
      '.MEEEEEM',
      'M.MMMM.M',
      'M......M',
    ],
    palette: { skin: '#a5bd72', core: '#355b4b', detail: '#e8d28b', accent: '#23384b' },
  },
  {
    id: 'iron-wolf',
    dex: 3,
    name: 'Rivetjack',
    primaryDiscipline: 'technique',
    secondaryDiscipline: 'endurance',
    visualConcept: 'A lean jackal-shaped tactician with rivet spots and a counterweight tail.',
    silhouette: 'Tall split ears, narrow waist, pointed muzzle, and a straight weighted tail.',
    personality: 'Observant, dryly playful, and fascinated by repeatable movement patterns.',
    habitat: 'Starter Link Road railings and the cooler practice floor of Starter Gym B.',
    gameplayRole: 'A control specialist that wins long exchanges through efficient counters.',
    baseHp: 42,
    power: 24,
    control: 84,
    stamina: 68,
    form: 19,
    mobility: 15,
    volume: 5,
    growthProfile: {
      id: 'growth-rivetjack',
      curve: 'steady',
      emphasizedStats: ['control', 'form', 'mobility'],
      description: 'Develops control and form evenly, with stamina arriving just behind them.',
    },
    captureDifficulty: 2,
    passiveAbility: {
      id: 'passive-rivet-read',
      name: 'Rivet Read',
      description: 'Learns an opponent’s rhythm and favors clean counters over rushed force.',
    },
    signatureMove: {
      id: 'move-centerline-switch',
      name: 'Centerline Switch',
      discipline: 'technique',
      description: 'Changes grip angle without surrendering the middle of the table.',
    },
    animations: animationReferences('iron-wolf'),
    flavor: 'It taps one tail weight against the floor whenever a partner’s form clicks into place.',
    isExotic: false,
    sprite: [
      'MM....MM',
      '.MM..MM.',
      '..MDDM..',
      '.MDEEDM.',
      '.MDDDDMM',
      '..MDDM.M',
      '..M..MMM',
      '.MM.....',
    ],
    palette: { skin: '#667681', core: '#283747', detail: '#e0b95f', accent: '#17222d' },
  },
  {
    id: 'muscled-boar',
    dex: 4,
    name: 'Kettusk',
    primaryDiscipline: 'power',
    secondaryDiscipline: 'endurance',
    visualConcept: 'A low kettle-bodied forager with mismatched tusks shaped like lifting handles.',
    silhouette: 'A round hanging torso, two hooked tusks, a short snout, and stamping feet.',
    personality: 'Blunt, eager, and happiest when given one clear task at a time.',
    habitat: 'Iron Gate Trail scrub and the reinforced lanes around Starter Gym B.',
    gameplayRole: 'A momentum breaker that applies heavy early pressure without becoming fragile.',
    baseHp: 50,
    power: 23,
    control: 44,
    stamina: 70,
    form: 11,
    mobility: 8,
    volume: 9,
    growthProfile: {
      id: 'growth-kettusk',
      curve: 'early-surge',
      emphasizedStats: ['power', 'stamina', 'volume'],
      description: 'Reaches a strong pressure profile early and grows durability afterward.',
    },
    captureDifficulty: 2,
    passiveAbility: {
      id: 'passive-set-bell',
      name: 'Set Bell',
      description: 'Builds confidence after committing to the same deliberate tempo.',
    },
    signatureMove: {
      id: 'move-handle-drive',
      name: 'Handle Drive',
      discipline: 'power',
      description: 'Hooks in close and converts a compact stance into a sudden table drive.',
    },
    animations: animationReferences('muscled-boar'),
    flavor: 'One tusk curls up and one curls down, so every grip station fits it differently.',
    isExotic: false,
    sprite: [
      '.MM..MM.',
      'MM.MMMM.',
      'MMDDEEMM',
      'MDDDDDDM',
      'MEDDDDEM',
      '.MDDDMM.',
      '.MM..MM.',
      'MM....MM',
    ],
    palette: { skin: '#bb704f', core: '#633326', detail: '#f0d297', accent: '#374b3a' },
  },
  {
    id: 'ripped-rhino',
    dex: 5,
    name: 'Railhorn',
    primaryDiscipline: 'power',
    secondaryDiscipline: 'technique',
    visualConcept: 'A slate-gray wedge runner with a rail-straight horn and padded forearms.',
    silhouette: 'One long forward horn, a sloped back, and parallel rectangular forearms.',
    personality: 'Focused, courteous, and unwilling to begin until the table is square.',
    habitat: 'Starter Gym A loading yard and the first rise of Iron Gate Trail.',
    gameplayRole: 'A precision striker with the roster’s strongest clean opening pressure.',
    baseHp: 49,
    power: 29,
    control: 66,
    stamina: 55,
    form: 17,
    mobility: 9,
    volume: 10,
    growthProfile: {
      id: 'growth-railhorn',
      curve: 'late-bloom',
      emphasizedStats: ['power', 'control', 'form'],
      description: 'Starts demanding, then gains exceptional force once its form matures.',
    },
    captureDifficulty: 3,
    passiveAbility: {
      id: 'passive-square-start',
      name: 'Square Start',
      description: 'Performs best when an encounter begins from a balanced, prepared position.',
    },
    signatureMove: {
      id: 'move-rail-line',
      name: 'Rail Line',
      discipline: 'technique',
      description: 'Aligns wrist, elbow, and shoulder into one uninterrupted pressure path.',
    },
    animations: animationReferences('ripped-rhino'),
    flavor: 'Its horn never points at a partner; before practice it turns sideways and bows.',
    isExotic: false,
    sprite: [
      '.....E..',
      '..MMMEM.',
      '.MDDDDMM',
      'MMDDDDEM',
      'MDDDDDMM',
      '.MDDDDM.',
      '.MM..MM.',
      'MM....MM',
    ],
    palette: { skin: '#89969a', core: '#3f5159', detail: '#d8b878', accent: '#27323a' },
  },
  {
    id: 'boulder-bison',
    dex: 6,
    name: 'Cairnox',
    primaryDiscipline: 'endurance',
    secondaryDiscipline: 'power',
    visualConcept: 'A patient herd Buddy with a stacked-stone hump and ring-shaped horns.',
    silhouette: 'Wide horn loops, a tall stepped hump, and four short pillar legs.',
    personality: 'Calm, communal, and known for pacing beside tired travelers.',
    habitat: 'Iron Gate Trail shelters and the stone perimeter of Iron Gym.',
    gameplayRole: 'A high-HP endurance wall that protects a team from long challenge attrition.',
    baseHp: 61,
    power: 27,
    control: 52,
    stamina: 88,
    form: 14,
    mobility: 6,
    volume: 11,
    growthProfile: {
      id: 'growth-cairnox',
      curve: 'late-bloom',
      emphasizedStats: ['baseHp', 'stamina', 'volume'],
      description: 'Accumulates slow, durable gains that peak in the longest encounters.',
    },
    captureDifficulty: 3,
    passiveAbility: {
      id: 'passive-trail-pacer',
      name: 'Trail Pacer',
      description: 'Maintains a steady effort when a challenge runs longer than expected.',
    },
    signatureMove: {
      id: 'move-cairn-hold',
      name: 'Cairn Hold',
      discipline: 'endurance',
      description: 'Stacks small position gains until the opponent has no easy route back.',
    },
    animations: animationReferences('boulder-bison'),
    flavor: 'Travelers add painted pebbles to its hump; it returns each one at the next shelter.',
    isExotic: false,
    sprite: [
      'MM....MM',
      'M.MMMM.M',
      '..MDDMM.',
      '.MDDDDMM',
      'MDDDDDMM',
      'MDDDDDDM',
      '.MM..MM.',
      'MM....MM',
    ],
    palette: { skin: '#806445', core: '#4d4034', detail: '#d9c28b', accent: '#293a42' },
  },
  {
    id: 'buff-otter',
    dex: 7,
    name: 'Rippleweld',
    primaryDiscipline: 'mobility',
    secondaryDiscipline: 'recovery',
    visualConcept: 'A sleek river-lane Buddy with a ribbon tail and luminous balance marks.',
    silhouette: 'Small round head, narrow torso, webbed feet, and one long curling tail.',
    personality: 'Inventive, social, and always testing a gentler route through hard movement.',
    habitat: 'Recovery Circuit channels and the hydration stops of Starter Link Road.',
    gameplayRole: 'A flexible reset specialist that supports fatigued teams and awkward matchups.',
    baseHp: 40,
    power: 21,
    control: 67,
    stamina: 61,
    form: 17,
    mobility: 22,
    volume: 4,
    growthProfile: {
      id: 'growth-rippleweld',
      curve: 'steady',
      emphasizedStats: ['control', 'form', 'mobility'],
      description: 'Gains mobility immediately and rounds out its technique with patient training.',
    },
    captureDifficulty: 2,
    passiveAbility: {
      id: 'passive-soft-reset',
      name: 'Soft Reset',
      description: 'Finds a stable neutral position after movement breaks down.',
    },
    signatureMove: {
      id: 'move-ribbon-regrip',
      name: 'Ribbon Regrip',
      discipline: 'mobility',
      description: 'Flows around a stalled wrist angle and returns with a safer hold.',
    },
    animations: animationReferences('buff-otter'),
    flavor: 'It knots its tail once for water, twice for rest, and never skips either signal.',
    isExotic: false,
    sprite: [
      '..MMMM..',
      '.MDEEDM.',
      '..MDDM..',
      '..MDDMM.',
      '..MDDM.M',
      '.M.MMM.M',
      'M.M..MMM',
      '.M......',
    ],
    palette: { skin: '#8c674f', core: '#366a75', detail: '#e5d094', accent: '#5eb6a8' },
  },
  {
    id: 'titan-gorilla',
    dex: 8,
    name: 'Knuckledge',
    primaryDiscipline: 'technique',
    secondaryDiscipline: 'power',
    visualConcept: 'An arch-backed climbing Buddy with chalk-white slab knuckles and a tiny waist.',
    silhouette: 'Long arms form a bridge around a narrow body; flat knuckles touch the ground.',
    personality: 'Quiet, studious, and delighted by a clever leverage solution.',
    habitat: 'Iron Gym gantries and the handrail cliffs above Forge Stretch.',
    gameplayRole: 'A leverage expert whose control and power peak after deliberate development.',
    baseHp: 52,
    power: 30,
    control: 78,
    stamina: 64,
    form: 20,
    mobility: 11,
    volume: 9,
    growthProfile: {
      id: 'growth-knuckledge',
      curve: 'late-bloom',
      emphasizedStats: ['power', 'control', 'form'],
      description: 'Needs technical investment before its excellent leverage fully arrives.',
    },
    captureDifficulty: 4,
    passiveAbility: {
      id: 'passive-leverage-lesson',
      name: 'Leverage Lesson',
      description: 'Turns careful form into pressure instead of relying on raw acceleration.',
    },
    signatureMove: {
      id: 'move-bridge-and-turn',
      name: 'Bridge and Turn',
      discipline: 'technique',
      description: 'Builds a stable arm bridge, then rotates from the strongest available angle.',
    },
    animations: animationReferences('titan-gorilla'),
    flavor: 'Its chalk prints resemble little maps, and young Buddies follow them as practice routes.',
    isExotic: false,
    sprite: [
      '..MMMM..',
      '.MDEEDM.',
      'MMDDDDMM',
      'M.MDDM.M',
      'M.MDDM.M',
      'M..MM..M',
      'EE.M..EE',
      'MM....MM',
    ],
    palette: { skin: '#66594f', core: '#30343a', detail: '#e8ddbd', accent: '#b67a52' },
  },
  {
    id: 'loopstride',
    dex: 9,
    name: 'Loopstride',
    primaryDiscipline: 'mobility',
    secondaryDiscipline: 'technique',
    visualConcept: 'A spring-legged lane runner whose looped ears act as balance gyros.',
    silhouette: 'Two enormous loop ears, a pinched torso, and oversized crescent feet.',
    personality: 'Curious, quick to volunteer, and serious about leaving room for others.',
    habitat: 'Starter Link Road interval flags and the open turns of Champion Ascent.',
    gameplayRole: 'The fastest repositioner, trading bulk for exceptional mobility and form.',
    baseHp: 35,
    power: 20,
    control: 75,
    stamina: 62,
    form: 20,
    mobility: 23,
    volume: 3,
    growthProfile: {
      id: 'growth-loopstride',
      curve: 'early-surge',
      emphasizedStats: ['control', 'form', 'mobility'],
      description: 'Reaches high movement quality early but needs time to build staying power.',
    },
    captureDifficulty: 2,
    passiveAbility: {
      id: 'passive-open-lane',
      name: 'Open Lane',
      description: 'Excels when it has room to reset its feet and choose a new angle.',
    },
    signatureMove: {
      id: 'move-loop-step',
      name: 'Loop Step',
      discipline: 'mobility',
      description: 'Circles through a compact foot pattern to change the direction of pressure.',
    },
    animations: animationReferences('loopstride'),
    flavor: 'Its ears hum softly at a balanced pace and go silent the moment a partner needs space.',
    isExotic: false,
    sprite: [
      '.MM..MM.',
      'M.M..M.M',
      'M.MMMM.M',
      '.MDEEDM.',
      '..MDDM..',
      '..MDDM..',
      '.MM..MM.',
      'MM....MM',
    ],
    palette: { skin: '#c89d67', core: '#465b7a', detail: '#f0d97e', accent: '#6fd0b0' },
  },
  {
    id: 'mendlume',
    dex: 10,
    name: 'Mendlume',
    primaryDiscipline: 'recovery',
    secondaryDiscipline: 'technique',
    visualConcept: 'A low salamander-like caretaker with a soft lantern crest and padded fingers.',
    silhouette: 'Glowing teardrop crest, long low body, four round hands, and a curled tail.',
    personality: 'Attentive, unhurried, and happiest when everyone finishes feeling capable.',
    habitat: 'Home Gym recovery nooks and the warm vents along Forge Stretch.',
    gameplayRole: 'The roster’s purest recovery support with high control and modest offense.',
    baseHp: 46,
    power: 19,
    control: 74,
    stamina: 72,
    form: 18,
    mobility: 14,
    volume: 4,
    growthProfile: {
      id: 'growth-mendlume',
      curve: 'steady',
      emphasizedStats: ['baseHp', 'control', 'stamina'],
      description: 'Builds reliable support values evenly and avoids dramatic weak periods.',
    },
    captureDifficulty: 2,
    passiveAbility: {
      id: 'passive-cooldown-glow',
      name: 'Cooldown Glow',
      description: 'Signals a calmer pace when accumulated effort begins to overwhelm the team.',
    },
    signatureMove: {
      id: 'move-lantern-release',
      name: 'Lantern Release',
      discipline: 'recovery',
      description: 'Relaxes excess tension, restores alignment, and resumes from a cleaner hold.',
    },
    animations: animationReferences('mendlume'),
    flavor: 'Its crest brightens near a safe resting place, even when the route signs are hidden.',
    isExotic: false,
    sprite: [
      '...E....',
      '..EDE...',
      '.MDDDM..',
      'MMDEEDMM',
      'MDDDDDMM',
      '.MDDM..M',
      'MM..MMMM',
      'M.......',
    ],
    palette: { skin: '#7c9b79', core: '#36544c', detail: '#f3d47a', accent: '#a7e0ae' },
  },
  {
    id: 'cadenswoop',
    dex: 11,
    name: 'Cadenswoop',
    primaryDiscipline: 'endurance',
    secondaryDiscipline: 'mobility',
    visualConcept: 'A metronome-legged glider with a striped wing cape and counter-beat crest.',
    silhouette: 'Wide triangular wings, a needle beak, two very long legs, and a rear crest.',
    personality: 'Upbeat, dependable, and always counting a sustainable rhythm out loud.',
    habitat: 'Champion Ascent wind lanes and the banner rafters of Glory Gym.',
    gameplayRole: 'A mobile endurance specialist that keeps consistent pressure across many rounds.',
    baseHp: 43,
    power: 23,
    control: 64,
    stamina: 90,
    form: 16,
    mobility: 20,
    volume: 5,
    growthProfile: {
      id: 'growth-cadenswoop',
      curve: 'late-bloom',
      emphasizedStats: ['stamina', 'form', 'mobility'],
      description: 'Its pace looks modest early, then becomes exceptional in extended challenges.',
    },
    captureDifficulty: 3,
    passiveAbility: {
      id: 'passive-even-cadence',
      name: 'Even Cadence',
      description: 'Holds a repeatable tempo when fatigue would normally disrupt timing.',
    },
    signatureMove: {
      id: 'move-switchback-sweep',
      name: 'Switchback Sweep',
      discipline: 'mobility',
      description: 'Uses a long controlled arc to redirect pressure without losing pace.',
    },
    animations: animationReferences('cadenswoop'),
    flavor: 'Hikers match its wingbeat when the summit path feels longer than the map promised.',
    isExotic: false,
    sprite: [
      '...EEM..',
      '..MDDM..',
      'MMMDDEMM',
      'M.MDDM.M',
      '..MDDM..',
      '...MM...',
      '..M..M..',
      '.MM..MM.',
    ],
    palette: { skin: '#5d718d', core: '#2e4058', detail: '#e3bd62', accent: '#d9e4d1' },
  },
  {
    id: 'spotmole',
    dex: 12,
    name: 'Spotmole',
    primaryDiscipline: 'recovery',
    secondaryDiscipline: 'power',
    visualConcept: 'A squat tunnel spotter with bright shovel palms and a soft safety-collar ruff.',
    silhouette: 'Tiny eyes, a huge circular ruff, two shovel hands, and almost invisible feet.',
    personality: 'Practical, encouraging, and impossible to embarrass with an imperfect attempt.',
    habitat: 'Iron Gym underworks and marked rest burrows beneath Iron Gate Trail.',
    gameplayRole: 'A durable safety specialist that combines recovery utility with emergency force.',
    baseHp: 57,
    power: 25,
    control: 57,
    stamina: 77,
    form: 15,
    mobility: 6,
    volume: 10,
    growthProfile: {
      id: 'growth-spotmole',
      curve: 'early-surge',
      emphasizedStats: ['baseHp', 'power', 'stamina'],
      description: 'Becomes sturdy very quickly, then improves control through continued practice.',
    },
    captureDifficulty: 2,
    passiveAbility: {
      id: 'passive-ready-spot',
      name: 'Ready Spot',
      description: 'Stays prepared to stabilize a partner when an attempt loses its safe line.',
    },
    signatureMove: {
      id: 'move-burrow-brace',
      name: 'Burrow Brace',
      discipline: 'recovery',
      description: 'Drops to a compact base and turns a failing angle into a secure reset.',
    },
    animations: animationReferences('spotmole'),
    flavor: 'It keeps lost gloves in dry burrows and returns them neatly paired.',
    isExotic: false,
    sprite: [
      '..MMMM..',
      '.MDEEDM.',
      'MMDDDDMM',
      'MDDDDDDM',
      'EEDDDDEE',
      'EMMDDMME',
      '..MMMM..',
      '..M..M..',
    ],
    palette: { skin: '#715947', core: '#3b3030', detail: '#e5c58b', accent: '#e88b62' },
  },
  {
    id: 'prismantle',
    dex: 50,
    name: 'Prismantle',
    primaryDiscipline: 'technique',
    secondaryDiscipline: 'mobility',
    visualConcept: 'An exotic floating mantle whose jointed ribbon fins fold into precise prisms.',
    silhouette: 'A diamond head, enormous angular fins, no visible legs, and a split ribbon tail.',
    personality: 'Formal, enigmatic, and willing to repeat a lesson until its pattern is understood.',
    habitat: 'Rare light pockets above Forge Stretch and the mirrored gallery of Apex Gym.',
    gameplayRole: 'An exotic counter specialist with elite control, form, and repositioning.',
    baseHp: 45,
    power: 34,
    control: 94,
    stamina: 71,
    form: 22,
    mobility: 21,
    volume: 5,
    growthProfile: {
      id: 'growth-prismantle',
      curve: 'late-bloom',
      emphasizedStats: ['control', 'form', 'mobility'],
      description: 'Demands patient training before its unusually high technical ceiling appears.',
    },
    captureDifficulty: 5,
    passiveAbility: {
      id: 'passive-facet-memory',
      name: 'Facet Memory',
      description: 'Remembers successful alignment patterns and favors repeating their clean geometry.',
    },
    signatureMove: {
      id: 'move-prism-fold',
      name: 'Prism Fold',
      discipline: 'technique',
      description: 'Folds three movement lines into one exact turn at the center of the table.',
    },
    animations: animationReferences('prismantle'),
    flavor: 'Each fin reflects a different training stance, but none show the viewer’s face.',
    isExotic: true,
    sprite: [
      '...EE...',
      '..EMME..',
      '.EMDDME.',
      'EMDDDDME',
      'M.MDDM.M',
      '..MDDM..',
      '.MM..MM.',
      'M......M',
    ],
    palette: { skin: '#8c77cc', core: '#3d356e', detail: '#f1d67f', accent: '#73d4c4' },
  },
  {
    id: 'vaultwyrm',
    dex: 51,
    name: 'Vaultwyrm',
    primaryDiscipline: 'endurance',
    secondaryDiscipline: 'recovery',
    visualConcept: 'An exotic ring-bodied sky serpent that forms a protective training arch.',
    silhouette: 'One hollow body loop, a small crest head, and a tail that closes like a clasp.',
    personality: 'Ancient-seeming, gentle, and stubborn about complete rest between hard efforts.',
    habitat: 'The highest rest arches of Champion Ascent and Glory Gym’s quiet upper vault.',
    gameplayRole: 'An exotic resilience engine with exceptional HP, stamina, and recovery identity.',
    baseHp: 68,
    power: 38,
    control: 73,
    stamina: 96,
    form: 17,
    mobility: 13,
    volume: 11,
    growthProfile: {
      id: 'growth-vaultwyrm',
      curve: 'late-bloom',
      emphasizedStats: ['baseHp', 'stamina', 'volume'],
      description: 'Grows slowly into the roster’s most durable long-challenge specialist.',
    },
    captureDifficulty: 5,
    passiveAbility: {
      id: 'passive-shelter-arc',
      name: 'Shelter Arc',
      description: 'Favors team stability after recovery has been treated as part of the plan.',
    },
    signatureMove: {
      id: 'move-vaulted-hold',
      name: 'Vaulted Hold',
      discipline: 'endurance',
      description: 'Builds a circular brace that becomes harder to unwind with every count.',
    },
    animations: animationReferences('vaultwyrm'),
    flavor: 'Old route markers were built beneath its resting coils, never the other way around.',
    isExotic: true,
    sprite: [
      '..MMME..',
      '.MDDDM..',
      'MDD..DM.',
      'MD....DM',
      'MD....DM',
      'MDD..DDM',
      '.MDDDDM.',
      '..MMMM..',
    ],
    palette: { skin: '#577b72', core: '#243e46', detail: '#d9c681', accent: '#9dd7c0' },
  },
  {
    id: 'crownquill',
    dex: 52,
    name: 'Crownquill',
    primaryDiscipline: 'power',
    secondaryDiscipline: 'technique',
    visualConcept: 'An exotic four-footed challenger crowned by movable quills and piston forelegs.',
    silhouette: 'A high radial crown, wedge chest, two massive forelegs, and two pin feet.',
    personality: 'Ceremonial, competitive, and meticulous about acknowledging a worthy challenge.',
    habitat: 'Apex Gym pressure chambers and the rare-signal terraces of Champion Ascent.',
    gameplayRole: 'An exotic finisher with immense force that still rewards disciplined setup.',
    baseHp: 56,
    power: 40,
    control: 81,
    stamina: 69,
    form: 19,
    mobility: 12,
    volume: 12,
    growthProfile: {
      id: 'growth-crownquill',
      curve: 'late-bloom',
      emphasizedStats: ['power', 'control', 'volume'],
      description: 'Its best pressure arrives late and only after a strong control foundation.',
    },
    captureDifficulty: 5,
    passiveAbility: {
      id: 'passive-honor-set',
      name: 'Honor Set',
      description: 'Commits fully when both competitors enter a challenge prepared.',
    },
    signatureMove: {
      id: 'move-crown-drive',
      name: 'Crown Drive',
      discipline: 'power',
      description: 'Fans its quills for balance before channeling a single decisive drive.',
    },
    animations: animationReferences('crownquill'),
    flavor: 'A fallen crown-quill is placed beside the route for whoever next needs courage.',
    isExotic: true,
    sprite: [
      'M.MMM.M.',
      '.MEMEM..',
      '..MDDM..',
      '.MDDDDM.',
      'MMDDDDEE',
      'MMDDDDMM',
      'MM....MM',
      'MM....MM',
    ],
    palette: { skin: '#a14f65', core: '#4f2942', detail: '#f2ca70', accent: '#e7e4c4' },
  },
  {
    id: 'manyfold',
    dex: 53,
    name: 'Manyfold',
    primaryDiscipline: 'recovery',
    secondaryDiscipline: 'mobility',
    visualConcept: 'An exotic folded-cloth being whose extra limbs unfold only to support a partner.',
    silhouette: 'An asymmetrical hood, four staggered arms, two ribbon legs, and one empty center fold.',
    personality: 'Kind, inscrutable, and constantly rearranging itself to make a safer shape.',
    habitat: 'Hidden recovery alcoves in Apex Gym and soft-banner caverns below Glory Lift.',
    gameplayRole: 'An exotic adaptive support that combines recovery, movement, and strong form.',
    baseHp: 53,
    power: 36,
    control: 86,
    stamina: 80,
    form: 23,
    mobility: 20,
    volume: 7,
    growthProfile: {
      id: 'growth-manyfold',
      curve: 'steady',
      emphasizedStats: ['control', 'form', 'mobility'],
      description: 'Develops a broad support profile steadily, with no single abrupt power spike.',
    },
    captureDifficulty: 5,
    passiveAbility: {
      id: 'passive-spare-hand',
      name: 'Spare Hand',
      description: 'Always seems to have one more stable contact point when a position unravels.',
    },
    signatureMove: {
      id: 'move-four-corner-reset',
      name: 'Four-Corner Reset',
      discipline: 'recovery',
      description: 'Unfolds around the table and guides the exchange back to a balanced center.',
    },
    animations: animationReferences('manyfold'),
    flavor: 'No two witnesses agree on its number of arms, but every account mentions a careful spot.',
    isExotic: true,
    sprite: [
      '..MMMM..',
      '.MDEEDM.',
      'M.MDDM..',
      '.MMDDMMM',
      'MM.DD.MM',
      '.MMDDM..',
      'M..MM.MM',
      '.MM..M..',
    ],
    palette: { skin: '#6c669d', core: '#34335d', detail: '#e8c879', accent: '#72baa4' },
  },
];

export const BUDDY_SPECIES_BY_ID = new Map(
  BUDDY_SPECIES.map((species) => [species.id, species]),
);
export const BUDDY_SPECIES_BY_DEX = new Map(
  BUDDY_SPECIES.map((species) => [species.dex, species]),
);

export const LEGACY_BUDDY_SPECIES_ID_MAP: Readonly<Record<string, string>> = {
  'slycera-griffin': 'prismantle',
  'cinder-manticore': 'vaultwyrm',
  'hydra-lurcher': 'crownquill',
  'pygmy-sable-pegasus': 'manyfold',
};

export const LEGACY_BUDDY_DEX_MAP: Readonly<Record<number, number>> = {
  54: 8,
};

export const STARTER_BUDDIES: StarterBuddyDefinition[] = [
  { id: 'starter-bramblift', speciesId: 'brawny-bear', seed: 1, level: 5 },
  { id: 'starter-plastrong', speciesId: 'titan-tortoise', seed: 2, level: 4 },
];

export const FANCY_NAMES = [
  'Chalk Comet',
  'Tempo Scout',
  'Mat Marvel',
  'Grip Guide',
  'Plate Poet',
  'Route Spark',
  'Form Friend',
  'Set Captain',
  'Rest Ranger',
  'Cadence Ace',
  'Spot Star',
  'Warmup Wonder',
  'Loop Legend',
];

export function getBuddySpeciesById(id: string) {
  const canonicalId = LEGACY_BUDDY_SPECIES_ID_MAP[id] ?? id;
  const species = BUDDY_SPECIES_BY_ID.get(canonicalId);
  if (!species) {
    throw new Error(`Unknown Buddy species "${id}".`);
  }
  return species;
}

export function normalizeBuddyDex(dex: number) {
  return LEGACY_BUDDY_DEX_MAP[dex] ?? dex;
}

export function normalizeBuddyDexList(dexEntries: readonly number[]) {
  return [...new Set(dexEntries.map(normalizeBuddyDex))];
}

type StoredBuddySpecies = Partial<BuddySpecies> & Pick<BuddySpecies, 'dex'>;

function recoveredText(
  value: unknown,
  fallback: string,
  maximumLength: number,
) {
  return typeof value === 'string'
    ? value.slice(0, maximumLength)
    : fallback;
}

export function resolveBuddySpeciesIdentity(species: StoredBuddySpecies): BuddySpecies {
  const storedId = species.id;
  const canonicalId = storedId
    ? LEGACY_BUDDY_SPECIES_ID_MAP[storedId] ?? storedId
    : undefined;
  const byId = canonicalId ? BUDDY_SPECIES_BY_ID.get(canonicalId) : undefined;
  if (byId) return byId;

  const normalizedDex = normalizeBuddyDex(species.dex);
  const byDex = BUDDY_SPECIES_BY_DEX.get(normalizedDex);
  if (byDex) return byDex;

  const fallback = BUDDY_SPECIES[0];
  const fallbackId = `legacy-dex-${normalizedDex}`;
  const recoveredId =
    typeof canonicalId === 'string' &&
    /^[a-z0-9][a-z0-9-]{0,63}$/.test(canonicalId)
      ? canonicalId
      : fallbackId;
  return {
    ...fallback,
    id: recoveredId,
    dex: normalizedDex,
    name: recoveredText(
      species.name,
      `Archived Buddy #${normalizedDex}`,
      48,
    ),
    visualConcept: recoveredText(
      species.visualConcept,
      'A legacy Buddy awaiting a refreshed visual concept.',
      240,
    ),
    silhouette: recoveredText(
      species.silhouette,
      'Legacy silhouette pending review.',
      160,
    ),
    personality: recoveredText(
      species.personality,
      'Its full profile has not been restored yet.',
      240,
    ),
    habitat: recoveredText(
      species.habitat,
      'Archived save data.',
      160,
    ),
    gameplayRole: recoveredText(
      species.gameplayRole,
      'Legacy all-rounder.',
      160,
    ),
    animations: animationReferences(fallbackId),
    flavor: recoveredText(
      species.flavor,
      'This Buddy traveled here from an earlier save.',
      240,
    ),
  };
}
