import type {
  CharacterAppearanceRecipe,
  MuscularBodyArchetype,
  NpcAppearanceTemplate,
  NpcCharacterSeed,
  NpcOutfitCombination,
  WorldCharacterDesign,
} from '../types';

export const MUSCULAR_BODY_ARCHETYPES: MuscularBodyArchetype[] = [
  {
    id: 'classic-bodybuilder',
    label: 'Classic Bodybuilder',
    physiquePresetId: 'classic-bodybuilder',
    silhouette: 'Tapered waist, round shoulders, balanced limbs.',
    strengthLanguage: 'Symmetry and deliberate posing communicate control.',
    posture: 'open',
  },
  {
    id: 'open-bodybuilder',
    label: 'Open-Mass Builder',
    physiquePresetId: 'open-bodybuilder',
    silhouette: 'High overall mass with rounded delts, thick limbs, and a controlled waist.',
    strengthLanguage: 'Stillness and compact posing make dense development readable without extra height.',
    posture: 'open',
  },
  {
    id: 'taper-performer',
    label: 'Taper Performer',
    physiquePresetId: 'taper-performer',
    silhouette: 'Long shoulder line and wide back over a compact waist.',
    strengthLanguage: 'Relaxed open posture keeps the taper visible during movement.',
    posture: 'open',
  },
  {
    id: 'sculpted-physique',
    label: 'Sculpted Physique',
    physiquePresetId: 'sculpted-physique',
    silhouette: 'Dense balanced limbs, rounded shoulders, and crisp torso separation.',
    strengthLanguage: 'Deliberate flex transitions communicate symmetry and control.',
    posture: 'upright',
  },
  {
    id: 'figure-balance',
    label: 'Figure Balance',
    physiquePresetId: 'figure-balance',
    silhouette: 'Round delts, a clear back taper, and developed legs.',
    strengthLanguage: 'Poised quarter turns and balanced stance communicate complete development.',
    posture: 'upright',
  },
  {
    id: 'heavy-powerlifter',
    label: 'Heavy Powerlifter',
    physiquePresetId: 'heavy-powerlifter',
    silhouette: 'Thick torso, grounded hips, dense upper back.',
    strengthLanguage: 'A braced stance communicates dependable force.',
    posture: 'grounded',
  },
  {
    id: 'strongman',
    label: 'Strongman',
    physiquePresetId: 'strongman',
    silhouette: 'Wide trunk, large hands, carry-ready shoulders.',
    strengthLanguage: 'Equipment and forward posture suggest practical power.',
    posture: 'forward',
  },
  {
    id: 'platform-lifter',
    label: 'Platform Lifter',
    physiquePresetId: 'platform-lifter',
    silhouette: 'Pronounced traps, braced back, powerful hips, and explosive legs.',
    strengthLanguage: 'A fast upright set position suggests precise whole-body force.',
    posture: 'grounded',
  },
  {
    id: 'balanced-athlete',
    label: 'Balanced Athlete',
    physiquePresetId: 'balanced-athlete',
    silhouette: 'Even proportions and a relaxed ready stance.',
    strengthLanguage: 'Economical movement communicates adaptable fitness.',
    posture: 'upright',
  },
  {
    id: 'lean-fighter',
    label: 'Lean Fighter',
    physiquePresetId: 'lean-fighter',
    silhouette: 'Long limbs, narrow waist, defined shoulders.',
    strengthLanguage: 'A coiled stance and quick guard communicate speed.',
    posture: 'coiled',
  },
  {
    id: 'lean-athlete',
    label: 'Lean Athletic',
    physiquePresetId: 'lean-athlete',
    silhouette: 'Long limbs, visible separation, and even athletic development.',
    strengthLanguage: 'Economical movement and a confident stride communicate usable strength.',
    posture: 'upright',
  },
  {
    id: 'compact-powerhouse',
    label: 'Compact Powerhouse',
    physiquePresetId: 'compact-powerhouse',
    silhouette: 'Short frame, broad chest, strong forearms.',
    strengthLanguage: 'Compressed proportions make every pose feel explosive.',
    posture: 'grounded',
  },
  {
    id: 'lower-body-specialist',
    label: 'Lower-Body Specialist',
    physiquePresetId: 'lower-body-specialist',
    silhouette: 'Powerful hips and legs with an athletic upper body.',
    strengthLanguage: 'A low stance communicates drive without extra height.',
    posture: 'coiled',
  },
  {
    id: 'upper-body-specialist',
    label: 'Upper-Body Specialist',
    physiquePresetId: 'upper-body-specialist',
    silhouette: 'Broad shoulders and arms with a stable base.',
    strengthLanguage: 'Open posture and arm placement communicate leverage.',
    posture: 'open',
  },
  {
    id: 'mobility-specialist',
    label: 'Mobility Specialist',
    physiquePresetId: 'lean-fighter',
    silhouette: 'Lean muscular frame with long, expressive movement lines.',
    strengthLanguage: 'Offset feet and relaxed joints communicate range.',
    posture: 'coiled',
  },
  {
    id: 'heavyweight-anchor',
    label: 'Heavyweight Anchor',
    physiquePresetId: 'heavy-powerlifter',
    silhouette: 'High body mass, broad waist, substantial legs.',
    strengthLanguage: 'Stillness, bracing, and calm timing communicate strength.',
    posture: 'grounded',
  },
];

const DEFAULT_RECIPE: CharacterAppearanceRecipe = {
  archetypeId: 'balanced-athlete',
  heightShift: 0,
  skinToneId: 'honey-warm',
  faceShapeId: 'oval-athletic',
  eyesId: 'focused-round',
  eyebrowsId: 'straight-bold',
  noseId: 'compact',
  mouthId: 'steady',
  facialHairId: 'none',
  hairStyleId: 'close-crop',
  hairLengthId: 'short',
  hairColorId: 'ink',
  topId: 'tank-racer',
  bottomsId: 'shorts-training',
  shoesId: 'trainer-low',
  glovesId: 'fingerless',
  wristWrapsId: 'single',
  headwearId: 'none',
  beltId: 'none',
  primaryColorId: 'teal',
  secondaryColorId: 'ink',
  accentColorId: 'amber',
};

function appearance(
  value: Partial<CharacterAppearanceRecipe>,
): CharacterAppearanceRecipe {
  return { ...DEFAULT_RECIPE, ...value };
}

type DerivedCharacterField =
  | 'handcrafted'
  | 'regionalMuscleEmphasis'
  | 'warmupAnimationId'
  | 'victoryPose'
  | 'lossReactionId'
  | 'signatureOutfitId'
  | 'alternateLateGameOutfit'
  | 'gymAccessoryId'
  | 'sponsorPatch';

function character(
  value: Omit<WorldCharacterDesign, DerivedCharacterField>,
): WorldCharacterDesign {
  const secondaryEmphasis = {
    power: 'shoulderWidth',
    technique: 'coreDefinition',
    endurance: 'quadSize',
    mobility: 'calfSize',
    recovery: 'upperBackWidth',
  } as const;
  const patchSymbol = {
    power: 'spark',
    technique: 'knot',
    endurance: 'anchor',
    mobility: 'arc',
    recovery: 'summit',
  } as const;
  return {
    ...value,
    regionalMuscleEmphasis: [
      value.primaryMuscleEmphasis,
      secondaryEmphasis[value.discipline],
    ],
    warmupAnimationId: `${value.id}-signature-warmup`,
    victoryPose: value.signaturePose,
    lossReactionId: `${value.id}-composed-reset`,
    signatureOutfitId: `${value.id}-signature-outfit`,
    alternateLateGameOutfit: {
      id: `${value.id}-late-game-outfit`,
      label: `${value.name} summit kit`,
      topId:
        value.appearance.topId.includes('hoodie')
          ? 'tank-racer'
          : 'hoodie-sleeveless',
      bottomsId:
        value.appearance.bottomsId === 'joggers-taper'
          ? 'shorts-training'
          : 'joggers-taper',
      primaryColorId: value.appearance.accentColorId,
      secondaryColorId: value.appearance.secondaryColorId,
      accentColorId: value.appearance.primaryColorId,
    },
    gymAccessoryId: `${value.id}-${value.discipline}-gym-token`,
    sponsorPatch: {
      id: `${value.id}-patch`,
      label: `${value.name} ${value.discipline} mark`,
      symbol: patchSymbol[value.discipline],
    },
    handcrafted: true,
  };
}

export const GYM_LEADER_CHARACTER_DESIGNS: WorldCharacterDesign[] = [
  character({
    id: 'character-coach-mara',
    name: 'Coach Mara',
    kind: 'gym-leader',
    discipline: 'recovery',
    appearance: appearance({
      archetypeId: 'figure-balance',
      skinToneId: 'mahogany-neutral',
      faceShapeId: 'broad-soft',
      eyesId: 'calm-wide',
      hairStyleId: 'locs-tied',
      hairLengthId: 'long',
      topId: 'hoodie-sleeveless',
      bottomsId: 'joggers-taper',
      shoesId: 'lifting-flat',
      glovesId: 'none',
      wristWrapsId: 'double',
      primaryColorId: 'moss',
      secondaryColorId: 'chalk',
      accentColorId: 'gold',
    }),
    idlePose: 'front-relaxed',
    expressionId: 'warm',
    primaryMuscleEmphasis: 'upperBackWidth',
    trainingPhilosophy: 'Recovery is an active part of every strong set.',
    signaturePose: 'back-double-biceps',
    signatureClothing: 'Moss sleeveless coaching hoodie',
    signatureEquipment: 'Twin pacing wraps',
    battleStance: 'Open palms and a planted recovery stance',
    entranceAnimationId: 'leader-mara-calm-step',
    idleAnimationId: 'leader-mara-lat-breath',
    victoryAnimationId: 'leader-mara-wrap-salute',
  }),
  character({
    id: 'character-grip-guide-dex',
    name: 'Grip Guide Dex',
    kind: 'gym-leader',
    discipline: 'power',
    appearance: appearance({
      archetypeId: 'compact-powerhouse',
      heightShift: -1,
      skinToneId: 'olive-gold',
      faceShapeId: 'square-strong',
      eyesId: 'determined-narrow',
      hairStyleId: 'buzz',
      topId: 'compression-short',
      shoesId: 'lifting-flat',
      glovesId: 'full-grip',
      wristWrapsId: 'long',
      beltId: 'lifting-wide',
      primaryColorId: 'coral',
      secondaryColorId: 'navy',
      accentColorId: 'chalk',
    }),
    idlePose: 'most-muscular',
    expressionId: 'bold',
    primaryMuscleEmphasis: 'forearmSize',
    trainingPhilosophy: 'Clean alignment turns a short effort into useful power.',
    signaturePose: 'side-triceps',
    signatureClothing: 'Coral compression top with navy side panels',
    signatureEquipment: 'Oversized white grip gloves',
    battleStance: 'Low elbows and square wrists',
    entranceAnimationId: 'leader-dex-knuckle-set',
    idleAnimationId: 'leader-dex-forearm-roll',
    victoryAnimationId: 'leader-dex-double-flex',
  }),
  character({
    id: 'character-control-coach-nia',
    name: 'Control Coach Nia',
    kind: 'gym-leader',
    discipline: 'technique',
    appearance: appearance({
      archetypeId: 'sculpted-physique',
      skinToneId: 'copper-rich',
      faceShapeId: 'diamond-defined',
      eyesId: 'sharp-upturn',
      hairStyleId: 'braids-back',
      hairLengthId: 'long',
      topId: 'tank-racer',
      bottomsId: 'leggings-panel',
      shoesId: 'wrap-shoes',
      glovesId: 'taped',
      headwearId: 'headband',
      primaryColorId: 'ocean',
      secondaryColorId: 'sky',
      accentColorId: 'amber',
    }),
    idlePose: 'front-relaxed',
    expressionId: 'focused',
    primaryMuscleEmphasis: 'shoulderWidth',
    trainingPhilosophy: 'Repeatable technique is strength you can trust.',
    signaturePose: 'front-double-biceps',
    signatureClothing: 'Ocean racer tank and paneled leggings',
    signatureEquipment: 'Amber line-marking hand tape',
    battleStance: 'High chest, angled feet, still centerline',
    entranceAnimationId: 'leader-nia-centerline-turn',
    idleAnimationId: 'leader-nia-delt-set',
    victoryAnimationId: 'leader-nia-measured-bow',
  }),
  character({
    id: 'character-gatekeeper-sol',
    name: 'Gatekeeper Sol',
    kind: 'gym-leader',
    discipline: 'endurance',
    appearance: appearance({
      archetypeId: 'strongman',
      heightShift: 1,
      skinToneId: 'umber-warm',
      faceShapeId: 'round-power',
      eyesId: 'deep-set',
      hairStyleId: 'bald',
      hairLengthId: 'none',
      topId: 'hoodie-sleeveless',
      bottomsId: 'shorts-training',
      shoesId: 'boot-strong',
      glovesId: 'padded',
      beltId: 'lifting-wide',
      primaryColorId: 'brick',
      secondaryColorId: 'ink',
      accentColorId: 'copper',
    }),
    idlePose: 'front-relaxed',
    expressionId: 'measured',
    primaryMuscleEmphasis: 'lowerBackThickness',
    trainingPhilosophy: 'Restraint keeps hard work available for the final round.',
    signaturePose: 'most-muscular',
    signatureClothing: 'Rust sleeveless hood and reinforced boots',
    signatureEquipment: 'Weathered carry belt',
    battleStance: 'Forward lean behind a quiet guard',
    entranceAnimationId: 'leader-sol-gate-carry',
    idleAnimationId: 'leader-sol-braced-breath',
    victoryAnimationId: 'leader-sol-belt-release',
  }),
  character({
    id: 'character-apex-analyst-vale',
    name: 'Apex Analyst Vale',
    kind: 'gym-leader',
    discipline: 'mobility',
    appearance: appearance({
      archetypeId: 'taper-performer',
      heightShift: 1,
      skinToneId: 'sand-gold',
      faceShapeId: 'long-angular',
      eyesId: 'single-lid',
      hairStyleId: 'side-sweep',
      hairLengthId: 'medium',
      topId: 'compression-long',
      bottomsId: 'leggings-panel',
      shoesId: 'runner-light',
      glovesId: 'none',
      wristWrapsId: 'single',
      primaryColorId: 'violet',
      secondaryColorId: 'orchid',
      accentColorId: 'mint',
    }),
    idlePose: 'confident-walk',
    expressionId: 'reserved',
    primaryMuscleEmphasis: 'upperBackWidth',
    trainingPhilosophy: 'Position creates safe power before the opponent reacts.',
    signaturePose: 'side-chest',
    signatureClothing: 'Violet split-panel compression suit',
    signatureEquipment: 'Mint motion-reading wrist band',
    battleStance: 'Offset feet with a relaxed leading shoulder',
    entranceAnimationId: 'leader-vale-pivot-read',
    idleAnimationId: 'leader-vale-taper-turn',
    victoryAnimationId: 'leader-vale-quiet-point',
  }),
  character({
    id: 'character-summit-steward-ori',
    name: 'Summit Steward Ori',
    kind: 'gym-leader',
    discipline: 'recovery',
    appearance: appearance({
      archetypeId: 'open-bodybuilder',
      skinToneId: 'deep-ebony',
      faceShapeId: 'square-strong',
      eyesId: 'bright-arc',
      hairStyleId: 'coils-high',
      hairLengthId: 'medium',
      topId: 'tee-panel',
      bottomsId: 'joggers-taper',
      shoesId: 'trainer-high',
      glovesId: 'fingerless',
      beltId: 'champion-sash',
      primaryColorId: 'gold',
      secondaryColorId: 'chalk',
      accentColorId: 'teal',
    }),
    idlePose: 'front-relaxed',
    expressionId: 'warm',
    primaryMuscleEmphasis: 'chestSize',
    trainingPhilosophy: 'A complete team carries every discipline to the summit.',
    signaturePose: 'victory-flex',
    signatureClothing: 'Gold panel shirt and balanced champion sash',
    signatureEquipment: 'Five-band summit clasp',
    battleStance: 'Upright stance with five-point hand signal',
    entranceAnimationId: 'leader-ori-five-band-open',
    idleAnimationId: 'leader-ori-chest-rise',
    victoryAnimationId: 'leader-ori-summit-salute',
  }),
];

export const RIVAL_CHARACTER_DESIGNS: WorldCharacterDesign[] = [
  character({
    id: 'rival-joa-brace',
    name: 'Joa Brace',
    kind: 'rival',
    discipline: 'power',
    appearance: appearance({
      archetypeId: 'heavy-powerlifter',
      skinToneId: 'amber-neutral',
      faceShapeId: 'round-power',
      eyesId: 'determined-narrow',
      hairStyleId: 'mohawk-soft',
      hairLengthId: 'short',
      topId: 'compression-short',
      bottomsId: 'shorts-split',
      shoesId: 'lifting-flat',
      glovesId: 'taped',
      beltId: 'lifting-wide',
      primaryColorId: 'brick',
      secondaryColorId: 'ink',
      accentColorId: 'amber',
    }),
    idlePose: 'most-muscular',
    expressionId: 'fierce',
    primaryMuscleEmphasis: 'gluteSize',
    trainingPhilosophy: 'Commit to the opening, then own the recovery.',
    signaturePose: 'side-chest',
    signatureClothing: 'Brick lifting singlet over a short compression top',
    signatureEquipment: 'Square bronze lifting buckle',
    battleStance: 'Deep brace with elbows pulled close',
    entranceAnimationId: 'rival-joa-floor-stomp',
    idleAnimationId: 'rival-joa-brace-cycle',
    victoryAnimationId: 'rival-joa-buckle-tap',
  }),
  character({
    id: 'rival-suri-tempo',
    name: 'Suri Tempo',
    kind: 'rival',
    discipline: 'technique',
    appearance: appearance({
      archetypeId: 'lean-athlete',
      skinToneId: 'rose-brown',
      faceShapeId: 'oval-athletic',
      eyesId: 'sharp-upturn',
      hairStyleId: 'top-knot',
      hairLengthId: 'long',
      topId: 'tank-racer',
      bottomsId: 'leggings-panel',
      shoesId: 'wrap-shoes',
      glovesId: 'fingerless',
      headwearId: 'wide-headband',
      primaryColorId: 'teal',
      secondaryColorId: 'navy',
      accentColorId: 'coral',
    }),
    idlePose: 'pre-workout-warmup',
    expressionId: 'playful',
    primaryMuscleEmphasis: 'coreDefinition',
    trainingPhilosophy: 'A readable rhythm can still hide a clever counter.',
    signaturePose: 'abs-and-thigh',
    signatureClothing: 'Teal split tank and coral tempo band',
    signatureEquipment: 'Three-count wrist clicker',
    battleStance: 'Loose guard with a bouncing lead heel',
    entranceAnimationId: 'rival-suri-three-count',
    idleAnimationId: 'rival-suri-shoulder-sweep',
    victoryAnimationId: 'rival-suri-spin-flex',
  }),
  character({
    id: 'rival-ren-lantern',
    name: 'Ren Lantern',
    kind: 'rival',
    discipline: 'recovery',
    appearance: appearance({
      archetypeId: 'platform-lifter',
      skinToneId: 'ivory-neutral',
      faceShapeId: 'broad-soft',
      eyesId: 'calm-wide',
      hairStyleId: 'fade-curl',
      hairLengthId: 'short',
      topId: 'hoodie-training',
      bottomsId: 'joggers-taper',
      shoesId: 'trainer-high',
      glovesId: 'none',
      wristWrapsId: 'double',
      primaryColorId: 'plum',
      secondaryColorId: 'chalk',
      accentColorId: 'mint',
    }),
    idlePose: 'back-relaxed',
    expressionId: 'steady',
    primaryMuscleEmphasis: 'trapeziusSize',
    trainingPhilosophy: 'Patience turns the longest journey into repeatable work.',
    signaturePose: 'back-double-biceps',
    signatureClothing: 'Plum training hoodie with mint lantern seam',
    signatureEquipment: 'Soft-light recovery timer',
    battleStance: 'Centered feet and low relaxed shoulders',
    entranceAnimationId: 'rival-ren-lantern-rise',
    idleAnimationId: 'rival-ren-trap-breath',
    victoryAnimationId: 'rival-ren-cooldown-wave',
  }),
];

export const NPC_OUTFIT_COMBINATIONS: NpcOutfitCombination[] = [
  {
    id: 'route-outfit-forge-carry',
    regionId: 'forge',
    topId: 'hoodie-sleeveless',
    bottomsId: 'joggers-taper',
    shoesId: 'lifting-flat',
    accessoryId: 'lifting-wide',
  },
  {
    id: 'route-outfit-forge-press',
    regionId: 'forge',
    topId: 'compression-short',
    bottomsId: 'shorts-training',
    shoesId: 'lifting-flat',
    accessoryId: 'double',
  },
  {
    id: 'route-outfit-ridge-tempo',
    regionId: 'ridge',
    topId: 'tank-racer',
    bottomsId: 'shorts-split',
    shoesId: 'runner-light',
    accessoryId: 'headband',
  },
  {
    id: 'route-outfit-ridge-control',
    regionId: 'ridge',
    topId: 'compression-long',
    bottomsId: 'leggings-panel',
    shoesId: 'wrap-shoes',
    accessoryId: 'single',
  },
  {
    id: 'route-outfit-summit-anchor',
    regionId: 'summit',
    topId: 'hoodie-training',
    bottomsId: 'joggers-taper',
    shoesId: 'trainer-high',
    accessoryId: 'beanie',
  },
  {
    id: 'route-outfit-summit-stride',
    regionId: 'summit',
    topId: 'tee-panel',
    bottomsId: 'leggings-panel',
    shoesId: 'runner-light',
    accessoryId: 'wide-headband',
  },
];

export const NPC_APPEARANCE_TEMPLATES: NpcAppearanceTemplate[] = [
  {
    id: 'npc-template-route-power',
    label: 'Route Power Trainer',
    archetypeIds: ['compact-powerhouse', 'heavy-powerlifter', 'strongman', 'open-bodybuilder'],
    disciplineIds: ['power', 'endurance'],
    skinToneIds: ['sand-gold', 'copper-rich', 'deep-ebony', 'olive-gold'],
    faceShapeIds: ['square-strong', 'round-power', 'broad-soft'],
    hairStyleIds: ['buzz', 'coils-high', 'bald', 'braids-back'],
    topIds: ['tank-racer', 'hoodie-sleeveless', 'compression-short'],
    bottomIds: ['shorts-training', 'joggers-taper'],
    accessoryIds: ['lifting-wide', 'headband', 'wide-headband'],
    facialHairIds: ['none', 'stubble', 'short-boxed'],
    eyebrowIds: ['straight-bold', 'angled-focus', 'soft-arc'],
    regionalOutfitIds: ['route-outfit-forge-carry', 'route-outfit-forge-press'],
    trainingSpecialtyIds: ['loaded-carry', 'press-control', 'ground-brace'],
    posePreferenceIds: ['most-muscular', 'side-chest', 'front-relaxed'],
    expressionIds: ['bold', 'focused', 'warm'],
    idlePoseIds: ['front-relaxed', 'most-muscular', 'post-set-pump'],
  },
  {
    id: 'npc-template-route-technique',
    label: 'Route Technique Trainer',
    archetypeIds: ['classic-bodybuilder', 'sculpted-physique', 'taper-performer', 'lean-athlete'],
    disciplineIds: ['technique', 'mobility'],
    skinToneIds: ['porcelain-warm', 'honey-warm', 'umber-warm', 'rose-brown'],
    faceShapeIds: ['oval-athletic', 'diamond-defined', 'long-angular'],
    hairStyleIds: ['waves', 'fade-curl', 'locs-tied', 'side-sweep'],
    topIds: ['tee-panel', 'tank-racer', 'compression-long'],
    bottomIds: ['shorts-split', 'leggings-panel'],
    accessoryIds: ['headband', 'single', 'none'],
    facialHairIds: ['none', 'stubble', 'mustache'],
    eyebrowIds: ['soft-arc', 'angled-focus', 'straight-bold'],
    regionalOutfitIds: ['route-outfit-ridge-tempo', 'route-outfit-ridge-control'],
    trainingSpecialtyIds: ['tempo-control', 'grip-switch', 'range-work'],
    posePreferenceIds: ['side-triceps', 'side-chest', 'front-double-biceps'],
    expressionIds: ['steady', 'playful', 'measured'],
    idlePoseIds: ['front-relaxed', 'side-chest', 'pre-workout-warmup'],
  },
  {
    id: 'npc-template-route-endurance',
    label: 'Route Endurance Trainer',
    archetypeIds: ['lower-body-specialist', 'figure-balance', 'platform-lifter', 'heavyweight-anchor'],
    disciplineIds: ['endurance', 'recovery'],
    skinToneIds: ['ivory-neutral', 'amber-neutral', 'mahogany-neutral', 'espresso-cool'],
    faceShapeIds: ['broad-soft', 'oval-athletic', 'round-power'],
    hairStyleIds: ['close-crop', 'top-knot', 'ponytail', 'bald'],
    topIds: ['hoodie-training', 'tee-panel', 'compression-short'],
    bottomIds: ['joggers-taper', 'leggings-panel'],
    accessoryIds: ['beanie', 'double', 'none'],
    facialHairIds: ['none', 'full-beard', 'stubble'],
    eyebrowIds: ['straight-bold', 'soft-arc', 'angled-focus'],
    regionalOutfitIds: ['route-outfit-summit-anchor', 'route-outfit-summit-stride'],
    trainingSpecialtyIds: ['route-pacing', 'recovery-carry', 'long-set'],
    posePreferenceIds: ['abs-and-thigh', 'back-double-biceps', 'back-relaxed'],
    expressionIds: ['warm', 'reserved', 'steady'],
    idlePoseIds: ['back-relaxed', 'abs-and-thigh', 'fatigued-stance'],
  },
];

export const NPC_CHARACTER_SEEDS: NpcCharacterSeed[] = [
  {
    id: 'character-stride-scout-rin',
    name: 'Stride Scout Rin',
    templateId: 'npc-template-route-technique',
    seed: 1101,
    trainingPhilosophy: 'Use the whole route to find an efficient stride.',
  },
  {
    id: 'character-form-marshal-kio',
    name: 'Form Marshal Kio',
    templateId: 'npc-template-route-power',
    seed: 2202,
    trainingPhilosophy: 'Heavy work stays useful when every rep has a shape.',
  },
  {
    id: 'character-trail-keeper-bo',
    name: 'Trail Keeper Bo',
    templateId: 'npc-template-route-endurance',
    seed: 3303,
    trainingPhilosophy: 'A steady route teaches what one hard burst cannot.',
  },
  {
    id: 'character-forge-reader-sela',
    name: 'Forge Reader Sela',
    templateId: 'npc-template-route-technique',
    seed: 4404,
    trainingPhilosophy: 'Read the environment before spending your strongest move.',
  },
  {
    id: 'character-summit-scout-ivo',
    name: 'Summit Scout Ivo',
    templateId: 'npc-template-route-endurance',
    seed: 5505,
    trainingPhilosophy: 'Arrive with enough left to appreciate the climb.',
  },
];

export const HANDCRAFTED_CHARACTER_DESIGNS = [
  ...GYM_LEADER_CHARACTER_DESIGNS,
  ...RIVAL_CHARACTER_DESIGNS,
];

export const MUSCULAR_BODY_ARCHETYPE_BY_ID = new Map(
  MUSCULAR_BODY_ARCHETYPES.map((entry) => [entry.id, entry]),
);

export const NPC_APPEARANCE_TEMPLATE_BY_ID = new Map(
  NPC_APPEARANCE_TEMPLATES.map((entry) => [entry.id, entry]),
);

export const NPC_OUTFIT_COMBINATION_BY_ID = new Map(
  NPC_OUTFIT_COMBINATIONS.map((entry) => [entry.id, entry]),
);

export const HANDCRAFTED_CHARACTER_BY_ID = new Map(
  HANDCRAFTED_CHARACTER_DESIGNS.map((entry) => [entry.id, entry]),
);

export const NPC_CHARACTER_SEED_BY_ID = new Map(
  NPC_CHARACTER_SEEDS.map((entry) => [entry.id, entry]),
);
