import type {
  CharacterAppearanceRecipe,
  MuscularBodyArchetype,
  NpcAppearanceTemplate,
  NpcCharacterSeed,
  WorldCharacterDesign,
} from '../types';

export const MUSCULAR_BODY_ARCHETYPES: MuscularBodyArchetype[] = [
  {
    id: 'classic-bodybuilder',
    label: 'Classic Bodybuilder',
    physiquePresetId: 'classic-bodybuilder',
    silhouette: 'Tapered waist, round shoulders, balanced limbs.',
    strengthLanguage: 'Symmetry and deliberate posing communicate control.',
    posture: 'open',
  },
  {
    id: 'heavy-powerlifter',
    label: 'Heavy Powerlifter',
    physiquePresetId: 'heavy-powerlifter',
    silhouette: 'Thick torso, grounded hips, dense upper back.',
    strengthLanguage: 'A braced stance communicates dependable force.',
    posture: 'grounded',
  },
  {
    id: 'strongman',
    label: 'Strongman',
    physiquePresetId: 'strongman',
    silhouette: 'Wide trunk, large hands, carry-ready shoulders.',
    strengthLanguage: 'Equipment and forward posture suggest practical power.',
    posture: 'forward',
  },
  {
    id: 'balanced-athlete',
    label: 'Balanced Athlete',
    physiquePresetId: 'balanced-athlete',
    silhouette: 'Even proportions and a relaxed ready stance.',
    strengthLanguage: 'Economical movement communicates adaptable fitness.',
    posture: 'upright',
  },
  {
    id: 'lean-fighter',
    label: 'Lean Fighter',
    physiquePresetId: 'lean-fighter',
    silhouette: 'Long limbs, narrow waist, defined shoulders.',
    strengthLanguage: 'A coiled stance and quick guard communicate speed.',
    posture: 'coiled',
  },
  {
    id: 'compact-powerhouse',
    label: 'Compact Powerhouse',
    physiquePresetId: 'compact-powerhouse',
    silhouette: 'Short frame, broad chest, strong forearms.',
    strengthLanguage: 'Compressed proportions make every pose feel explosive.',
    posture: 'grounded',
  },
  {
    id: 'lower-body-specialist',
    label: 'Lower-Body Specialist',
    physiquePresetId: 'lower-body-specialist',
    silhouette: 'Powerful hips and legs with an athletic upper body.',
    strengthLanguage: 'A low stance communicates drive without extra height.',
    posture: 'coiled',
  },
  {
    id: 'upper-body-specialist',
    label: 'Upper-Body Specialist',
    physiquePresetId: 'upper-body-specialist',
    silhouette: 'Broad shoulders and arms with a stable base.',
    strengthLanguage: 'Open posture and arm placement communicate leverage.',
    posture: 'open',
  },
  {
    id: 'mobility-specialist',
    label: 'Mobility Specialist',
    physiquePresetId: 'lean-fighter',
    silhouette: 'Lean muscular frame with long, expressive movement lines.',
    strengthLanguage: 'Offset feet and relaxed joints communicate range.',
    posture: 'coiled',
  },
  {
    id: 'heavyweight-anchor',
    label: 'Heavyweight Anchor',
    physiquePresetId: 'heavy-powerlifter',
    silhouette: 'High body mass, broad waist, substantial legs.',
    strengthLanguage: 'Stillness, bracing, and calm timing communicate strength.',
    posture: 'grounded',
  },
];

const DEFAULT_RECIPE: CharacterAppearanceRecipe = {
  archetypeId: 'balanced-athlete',
  heightShift: 0,
  skinToneId: 'honey-warm',
  faceShapeId: 'oval-athletic',
  eyesId: 'focused-round',
  hairStyleId: 'close-crop',
  hairLengthId: 'short',
  hairColorId: 'ink',
  topId: 'tank-racer',
  bottomsId: 'shorts-training',
  shoesId: 'trainer-low',
  glovesId: 'fingerless',
  wristWrapsId: 'single',
  headwearId: 'none',
  beltId: 'none',
  primaryColorId: 'teal',
  secondaryColorId: 'ink',
  accentColorId: 'amber',
};

function appearance(
  value: Partial<CharacterAppearanceRecipe>,
): CharacterAppearanceRecipe {
  return { ...DEFAULT_RECIPE, ...value };
}

function character(
  value: Omit<WorldCharacterDesign, 'handcrafted'>,
): WorldCharacterDesign {
  return { ...value, handcrafted: true };
}

export const GYM_LEADER_CHARACTER_DESIGNS: WorldCharacterDesign[] = [
  character({
    id: 'character-coach-mara',
    name: 'Coach Mara',
    kind: 'gym-leader',
    discipline: 'recovery',
    appearance: appearance({
      archetypeId: 'heavyweight-anchor',
      skinToneId: 'mahogany-neutral',
      faceShapeId: 'broad-soft',
      eyesId: 'calm-wide',
      hairStyleId: 'locs-tied',
      hairLengthId: 'long',
      topId: 'hoodie-sleeveless',
      bottomsId: 'joggers-taper',
      shoesId: 'lifting-flat',
      glovesId: 'none',
      wristWrapsId: 'double',
      primaryColorId: 'moss',
      secondaryColorId: 'chalk',
      accentColorId: 'gold',
    }),
    idlePose: 'idle',
    expressionId: 'warm',
    trainingPhilosophy: 'Recovery is an active part of every strong set.',
    signaturePose: 'training',
    signatureClothing: 'Moss sleeveless coaching hoodie',
    signatureEquipment: 'Twin pacing wraps',
    battleStance: 'Open palms and a planted recovery stance',
    entranceAnimationId: 'leader-mara-calm-step',
    victoryAnimationId: 'leader-mara-wrap-salute',
  }),
  character({
    id: 'character-grip-guide-dex',
    name: 'Grip Guide Dex',
    kind: 'gym-leader',
    discipline: 'power',
    appearance: appearance({
      archetypeId: 'compact-powerhouse',
      heightShift: -1,
      skinToneId: 'olive-gold',
      faceShapeId: 'square-strong',
      eyesId: 'determined-narrow',
      hairStyleId: 'buzz',
      topId: 'compression-short',
      shoesId: 'lifting-flat',
      glovesId: 'full-grip',
      wristWrapsId: 'long',
      beltId: 'lifting-wide',
      primaryColorId: 'coral',
      secondaryColorId: 'navy',
      accentColorId: 'chalk',
    }),
    idlePose: 'training',
    expressionId: 'bold',
    trainingPhilosophy: 'Clean alignment turns a short effort into useful power.',
    signaturePose: 'capture',
    signatureClothing: 'Coral compression top with navy side panels',
    signatureEquipment: 'Oversized white grip gloves',
    battleStance: 'Low elbows and square wrists',
    entranceAnimationId: 'leader-dex-knuckle-set',
    victoryAnimationId: 'leader-dex-double-flex',
  }),
  character({
    id: 'character-control-coach-nia',
    name: 'Control Coach Nia',
    kind: 'gym-leader',
    discipline: 'technique',
    appearance: appearance({
      archetypeId: 'classic-bodybuilder',
      skinToneId: 'copper-rich',
      faceShapeId: 'diamond-defined',
      eyesId: 'sharp-upturn',
      hairStyleId: 'braids-back',
      hairLengthId: 'long',
      topId: 'tank-racer',
      bottomsId: 'leggings-panel',
      shoesId: 'wrap-shoes',
      glovesId: 'taped',
      headwearId: 'headband',
      primaryColorId: 'ocean',
      secondaryColorId: 'sky',
      accentColorId: 'amber',
    }),
    idlePose: 'training',
    expressionId: 'focused',
    trainingPhilosophy: 'Repeatable technique is strength you can trust.',
    signaturePose: 'boss-introduction',
    signatureClothing: 'Ocean racer tank and paneled leggings',
    signatureEquipment: 'Amber line-marking hand tape',
    battleStance: 'High chest, angled feet, still centerline',
    entranceAnimationId: 'leader-nia-centerline-turn',
    victoryAnimationId: 'leader-nia-measured-bow',
  }),
  character({
    id: 'character-gatekeeper-sol',
    name: 'Gatekeeper Sol',
    kind: 'gym-leader',
    discipline: 'endurance',
    appearance: appearance({
      archetypeId: 'strongman',
      heightShift: 1,
      skinToneId: 'umber-warm',
      faceShapeId: 'round-power',
      eyesId: 'deep-set',
      hairStyleId: 'bald',
      hairLengthId: 'none',
      topId: 'hoodie-sleeveless',
      bottomsId: 'shorts-training',
      shoesId: 'boot-strong',
      glovesId: 'padded',
      beltId: 'lifting-wide',
      primaryColorId: 'brick',
      secondaryColorId: 'ink',
      accentColorId: 'copper',
    }),
    idlePose: 'fatigue',
    expressionId: 'measured',
    trainingPhilosophy: 'Restraint keeps hard work available for the final round.',
    signaturePose: 'training',
    signatureClothing: 'Rust sleeveless hood and reinforced boots',
    signatureEquipment: 'Weathered carry belt',
    battleStance: 'Forward lean behind a quiet guard',
    entranceAnimationId: 'leader-sol-gate-carry',
    victoryAnimationId: 'leader-sol-belt-release',
  }),
  character({
    id: 'character-apex-analyst-vale',
    name: 'Apex Analyst Vale',
    kind: 'gym-leader',
    discipline: 'mobility',
    appearance: appearance({
      archetypeId: 'mobility-specialist',
      heightShift: 1,
      skinToneId: 'sand-gold',
      faceShapeId: 'long-angular',
      eyesId: 'single-lid',
      hairStyleId: 'side-sweep',
      hairLengthId: 'medium',
      topId: 'compression-long',
      bottomsId: 'leggings-panel',
      shoesId: 'runner-light',
      glovesId: 'none',
      wristWrapsId: 'single',
      primaryColorId: 'violet',
      secondaryColorId: 'orchid',
      accentColorId: 'mint',
    }),
    idlePose: 'capture',
    expressionId: 'reserved',
    trainingPhilosophy: 'Position creates safe power before the opponent reacts.',
    signaturePose: 'boss-introduction',
    signatureClothing: 'Violet split-panel compression suit',
    signatureEquipment: 'Mint motion-reading wrist band',
    battleStance: 'Offset feet with a relaxed leading shoulder',
    entranceAnimationId: 'leader-vale-pivot-read',
    victoryAnimationId: 'leader-vale-quiet-point',
  }),
  character({
    id: 'character-summit-steward-ori',
    name: 'Summit Steward Ori',
    kind: 'gym-leader',
    discipline: 'recovery',
    appearance: appearance({
      archetypeId: 'balanced-athlete',
      skinToneId: 'deep-ebony',
      faceShapeId: 'square-strong',
      eyesId: 'bright-arc',
      hairStyleId: 'coils-high',
      hairLengthId: 'medium',
      topId: 'tee-panel',
      bottomsId: 'joggers-taper',
      shoesId: 'trainer-high',
      glovesId: 'fingerless',
      beltId: 'champion-sash',
      primaryColorId: 'gold',
      secondaryColorId: 'chalk',
      accentColorId: 'teal',
    }),
    idlePose: 'victory',
    expressionId: 'warm',
    trainingPhilosophy: 'A complete team carries every discipline to the summit.',
    signaturePose: 'victory',
    signatureClothing: 'Gold panel shirt and balanced champion sash',
    signatureEquipment: 'Five-band summit clasp',
    battleStance: 'Upright stance with five-point hand signal',
    entranceAnimationId: 'leader-ori-five-band-open',
    victoryAnimationId: 'leader-ori-summit-salute',
  }),
];

export const RIVAL_CHARACTER_DESIGNS: WorldCharacterDesign[] = [
  character({
    id: 'rival-joa-brace',
    name: 'Joa Brace',
    kind: 'rival',
    discipline: 'power',
    appearance: appearance({
      archetypeId: 'heavy-powerlifter',
      skinToneId: 'amber-neutral',
      faceShapeId: 'round-power',
      eyesId: 'determined-narrow',
      hairStyleId: 'mohawk-soft',
      hairLengthId: 'short',
      topId: 'compression-short',
      bottomsId: 'shorts-split',
      shoesId: 'lifting-flat',
      glovesId: 'taped',
      beltId: 'lifting-wide',
      primaryColorId: 'brick',
      secondaryColorId: 'ink',
      accentColorId: 'amber',
    }),
    idlePose: 'training',
    expressionId: 'fierce',
    trainingPhilosophy: 'Commit to the opening, then own the recovery.',
    signaturePose: 'capture',
    signatureClothing: 'Brick lifting singlet over a short compression top',
    signatureEquipment: 'Square bronze lifting buckle',
    battleStance: 'Deep brace with elbows pulled close',
    entranceAnimationId: 'rival-joa-floor-stomp',
    victoryAnimationId: 'rival-joa-buckle-tap',
  }),
  character({
    id: 'rival-suri-tempo',
    name: 'Suri Tempo',
    kind: 'rival',
    discipline: 'technique',
    appearance: appearance({
      archetypeId: 'lean-fighter',
      skinToneId: 'rose-brown',
      faceShapeId: 'oval-athletic',
      eyesId: 'sharp-upturn',
      hairStyleId: 'top-knot',
      hairLengthId: 'long',
      topId: 'tank-racer',
      bottomsId: 'leggings-panel',
      shoesId: 'wrap-shoes',
      glovesId: 'fingerless',
      headwearId: 'wide-headband',
      primaryColorId: 'teal',
      secondaryColorId: 'navy',
      accentColorId: 'coral',
    }),
    idlePose: 'capture',
    expressionId: 'playful',
    trainingPhilosophy: 'A readable rhythm can still hide a clever counter.',
    signaturePose: 'boss-introduction',
    signatureClothing: 'Teal split tank and coral tempo band',
    signatureEquipment: 'Three-count wrist clicker',
    battleStance: 'Loose guard with a bouncing lead heel',
    entranceAnimationId: 'rival-suri-three-count',
    victoryAnimationId: 'rival-suri-spin-flex',
  }),
  character({
    id: 'rival-ren-lantern',
    name: 'Ren Lantern',
    kind: 'rival',
    discipline: 'recovery',
    appearance: appearance({
      archetypeId: 'compact-powerhouse',
      skinToneId: 'ivory-neutral',
      faceShapeId: 'broad-soft',
      eyesId: 'calm-wide',
      hairStyleId: 'fade-curl',
      hairLengthId: 'short',
      topId: 'hoodie-training',
      bottomsId: 'joggers-taper',
      shoesId: 'trainer-high',
      glovesId: 'none',
      wristWrapsId: 'double',
      primaryColorId: 'plum',
      secondaryColorId: 'chalk',
      accentColorId: 'mint',
    }),
    idlePose: 'idle',
    expressionId: 'steady',
    trainingPhilosophy: 'Patience turns the longest journey into repeatable work.',
    signaturePose: 'victory',
    signatureClothing: 'Plum training hoodie with mint lantern seam',
    signatureEquipment: 'Soft-light recovery timer',
    battleStance: 'Centered feet and low relaxed shoulders',
    entranceAnimationId: 'rival-ren-lantern-rise',
    victoryAnimationId: 'rival-ren-cooldown-wave',
  }),
];

export const NPC_APPEARANCE_TEMPLATES: NpcAppearanceTemplate[] = [
  {
    id: 'npc-template-route-power',
    label: 'Route Power Trainer',
    archetypeIds: ['compact-powerhouse', 'heavy-powerlifter', 'strongman'],
    disciplineIds: ['power', 'endurance'],
    skinToneIds: ['sand-gold', 'copper-rich', 'deep-ebony', 'olive-gold'],
    faceShapeIds: ['square-strong', 'round-power', 'broad-soft'],
    hairStyleIds: ['buzz', 'coils-high', 'bald', 'braids-back'],
    topIds: ['tank-racer', 'hoodie-sleeveless', 'compression-short'],
    bottomIds: ['shorts-training', 'joggers-taper'],
    accessoryIds: ['lifting-wide', 'headband', 'wide-headband'],
    expressionIds: ['bold', 'focused', 'warm'],
    idlePoseIds: ['idle', 'training'],
  },
  {
    id: 'npc-template-route-technique',
    label: 'Route Technique Trainer',
    archetypeIds: ['classic-bodybuilder', 'balanced-athlete', 'lean-fighter'],
    disciplineIds: ['technique', 'mobility'],
    skinToneIds: ['porcelain-warm', 'honey-warm', 'umber-warm', 'rose-brown'],
    faceShapeIds: ['oval-athletic', 'diamond-defined', 'long-angular'],
    hairStyleIds: ['waves', 'fade-curl', 'locs-tied', 'side-sweep'],
    topIds: ['tee-panel', 'tank-racer', 'compression-long'],
    bottomIds: ['shorts-split', 'leggings-panel'],
    accessoryIds: ['headband', 'single', 'none'],
    expressionIds: ['steady', 'playful', 'measured'],
    idlePoseIds: ['idle', 'capture'],
  },
  {
    id: 'npc-template-route-endurance',
    label: 'Route Endurance Trainer',
    archetypeIds: ['lower-body-specialist', 'balanced-athlete', 'heavyweight-anchor'],
    disciplineIds: ['endurance', 'recovery'],
    skinToneIds: ['ivory-neutral', 'amber-neutral', 'mahogany-neutral', 'espresso-cool'],
    faceShapeIds: ['broad-soft', 'oval-athletic', 'round-power'],
    hairStyleIds: ['close-crop', 'top-knot', 'ponytail', 'bald'],
    topIds: ['hoodie-training', 'tee-panel', 'compression-short'],
    bottomIds: ['joggers-taper', 'leggings-panel'],
    accessoryIds: ['beanie', 'double', 'none'],
    expressionIds: ['warm', 'reserved', 'steady'],
    idlePoseIds: ['idle', 'fatigue'],
  },
];

export const NPC_CHARACTER_SEEDS: NpcCharacterSeed[] = [
  {
    id: 'character-stride-scout-rin',
    name: 'Stride Scout Rin',
    templateId: 'npc-template-route-technique',
    seed: 1101,
    trainingPhilosophy: 'Use the whole route to find an efficient stride.',
  },
  {
    id: 'character-form-marshal-kio',
    name: 'Form Marshal Kio',
    templateId: 'npc-template-route-power',
    seed: 2202,
    trainingPhilosophy: 'Heavy work stays useful when every rep has a shape.',
  },
  {
    id: 'character-trail-keeper-bo',
    name: 'Trail Keeper Bo',
    templateId: 'npc-template-route-endurance',
    seed: 3303,
    trainingPhilosophy: 'A steady route teaches what one hard burst cannot.',
  },
  {
    id: 'character-forge-reader-sela',
    name: 'Forge Reader Sela',
    templateId: 'npc-template-route-technique',
    seed: 4404,
    trainingPhilosophy: 'Read the environment before spending your strongest move.',
  },
  {
    id: 'character-summit-scout-ivo',
    name: 'Summit Scout Ivo',
    templateId: 'npc-template-route-endurance',
    seed: 5505,
    trainingPhilosophy: 'Arrive with enough left to appreciate the climb.',
  },
];

export const HANDCRAFTED_CHARACTER_DESIGNS = [
  ...GYM_LEADER_CHARACTER_DESIGNS,
  ...RIVAL_CHARACTER_DESIGNS,
];

export const MUSCULAR_BODY_ARCHETYPE_BY_ID = new Map(
  MUSCULAR_BODY_ARCHETYPES.map((entry) => [entry.id, entry]),
);

export const NPC_APPEARANCE_TEMPLATE_BY_ID = new Map(
  NPC_APPEARANCE_TEMPLATES.map((entry) => [entry.id, entry]),
);

export const HANDCRAFTED_CHARACTER_BY_ID = new Map(
  HANDCRAFTED_CHARACTER_DESIGNS.map((entry) => [entry.id, entry]),
);

export const NPC_CHARACTER_SEED_BY_ID = new Map(
  NPC_CHARACTER_SEEDS.map((entry) => [entry.id, entry]),
);
