import type { GymMachine } from '../types';

export const HOME_MACHINES: GymMachine[] = [
  {
    id: 'home_recovery',
    name: 'Recovery Rack',
    detail: 'Low-load activation, shoulder re-training, and mobility flow.',
    focus: 'Recovery',
    xpMin: 1,
    xpMax: 3,
    xpMultiplier: 1.0,
    steroidChance: 0.26,
    hpRestore: 5,
    fatigueCost: 0,
  },
  {
    id: 'home_dumbbells',
    name: 'Mobility Dumbbells',
    detail: 'Slow, controlled presses to tighten lock angles and control.',
    focus: 'Stability',
    xpMin: 1,
    xpMax: 4,
    xpMultiplier: 1.06,
    steroidChance: 0.22,
    hpRestore: 3,
    fatigueCost: 1,
  },
  {
    id: 'home_plate',
    name: 'Technique Plate Stack',
    detail: 'Mini-overload sets for clean elbow path and wrist lock.',
    focus: 'Control',
    xpMin: 1,
    xpMax: 5,
    xpMultiplier: 1.12,
    steroidChance: 0.18,
    hpRestore: 2,
    fatigueCost: 1,
  },
  {
    id: 'home_bike',
    name: 'Foam Roller Bike',
    detail: 'Light cardio + bloodflow recovery for training volume.',
    focus: 'Endurance',
    xpMin: 1,
    xpMax: 4,
    xpMultiplier: 1.05,
    steroidChance: 0.2,
    hpRestore: 4,
    fatigueCost: 1,
  },
];

export const STARTER_A_MACHINES: GymMachine[] = [
  {
    id: 'starter_a_bench',
    name: 'Flat Bench Press Rack',
    detail: 'Heavy pressing intervals for shoulder-endurance.',
    focus: 'Power',
    xpMin: 2,
    xpMax: 5,
    xpMultiplier: 1.18,
    steroidChance: 0.2,
    hpRestore: 2,
    fatigueCost: 2,
  },
  {
    id: 'starter_a_ropes',
    name: 'Rope Pulley Station',
    detail: 'Cable arcs teach wrist alignment and short reset speed.',
    focus: 'Grip',
    xpMin: 1,
    xpMax: 5,
    xpMultiplier: 1.15,
    steroidChance: 0.24,
    hpRestore: 2,
    fatigueCost: 2,
  },
  {
    id: 'starter_a_machine',
    name: 'Iso-Lock Cables',
    detail: 'Isometric holds for control under compression pressure.',
    focus: 'Lockout',
    xpMin: 2,
    xpMax: 6,
    xpMultiplier: 1.2,
    steroidChance: 0.18,
    hpRestore: 1,
    fatigueCost: 2,
  },
  {
    id: 'starter_a_rows',
    name: 'Hammer Strength Row',
    detail: 'Back and elbow path work for high-pressure grapples.',
    focus: 'Pull Power',
    xpMin: 2,
    xpMax: 6,
    xpMultiplier: 1.22,
    steroidChance: 0.2,
    hpRestore: 1,
    fatigueCost: 3,
  },
];

export const STARTER_B_MACHINES: GymMachine[] = [
  {
    id: 'starter_b_leg',
    name: 'Hack Squat Machine',
    detail: 'Lower-body chains for stable stance and power transfer.',
    focus: 'Base Drive',
    xpMin: 3,
    xpMax: 6,
    xpMultiplier: 1.23,
    steroidChance: 0.2,
    hpRestore: 1,
    fatigueCost: 3,
  },
  {
    id: 'starter_b_cable',
    name: 'Selectorized Pulley',
    detail: 'Continuous arcs for controlled acceleration work.',
    focus: 'Tempo',
    xpMin: 2,
    xpMax: 6,
    xpMultiplier: 1.16,
    steroidChance: 0.18,
    hpRestore: 2,
    fatigueCost: 2,
  },
  {
    id: 'starter_b_pulley',
    name: 'Pulley Wall Rig',
    detail: 'High-tension pulling with precision lockout timing.',
    focus: 'Timing',
    xpMin: 3,
    xpMax: 5,
    xpMultiplier: 1.21,
    steroidChance: 0.22,
    hpRestore: 2,
    fatigueCost: 2,
  },
  {
    id: 'starter_b_leg_pulse',
    name: 'Leg Press Power Stack',
    detail: 'Pump and recover in short rounds to raise fight-stamina.',
    focus: 'Endurance',
    xpMin: 3,
    xpMax: 7,
    xpMultiplier: 1.25,
    steroidChance: 0.18,
    hpRestore: 1,
    fatigueCost: 4,
  },
];

export const IRON_MACHINES: GymMachine[] = [
  {
    id: 'iron_armor',
    name: 'Smith Cage Press',
    detail: 'Guided barbell overload for dense, repeatable max-reps.',
    focus: 'Strength',
    xpMin: 3,
    xpMax: 8,
    xpMultiplier: 1.28,
    steroidChance: 0.2,
    hpRestore: 1,
    fatigueCost: 3,
  },
  {
    id: 'iron_row',
    name: 'Hammer Row Dynamo',
    detail: 'Engine-like back cycles for long fight rounds.',
    focus: 'Durability',
    xpMin: 4,
    xpMax: 7,
    xpMultiplier: 1.14,
    steroidChance: 0.22,
    hpRestore: 2,
    fatigueCost: 3,
  },
  {
    id: 'iron_chain',
    name: 'Chain Cable Stack',
    detail: 'Variable resistance for explosive lockout simulation.',
    focus: 'Lockout',
    xpMin: 4,
    xpMax: 8,
    xpMultiplier: 1.22,
    steroidChance: 0.17,
    hpRestore: 1,
    fatigueCost: 3,
  },
  {
    id: 'iron_grip',
    name: 'Fat Gripper Tower',
    detail: 'Thick handles and squeeze holds for late-round control.',
    focus: 'Grip',
    xpMin: 4,
    xpMax: 8,
    xpMultiplier: 1.24,
    steroidChance: 0.19,
    hpRestore: 1,
    fatigueCost: 4,
  },
];

export const APEX_MACHINES: GymMachine[] = [
  {
    id: 'apex_platform',
    name: 'Plate-Loaded Squeeze Press',
    detail: 'Near-perfect tension under fatigue, controlled plate microloads.',
    focus: 'Precision',
    xpMin: 4,
    xpMax: 9,
    xpMultiplier: 1.31,
    steroidChance: 0.2,
    hpRestore: 1,
    fatigueCost: 4,
  },
  {
    id: 'apex_blink',
    name: 'Functional Row Matrix',
    detail: 'Short cycles with explosive resets and reset speed.',
    focus: 'Rhythm',
    xpMin: 3,
    xpMax: 9,
    xpMultiplier: 1.23,
    steroidChance: 0.24,
    hpRestore: 2,
    fatigueCost: 3,
  },
  {
    id: 'apex_harness',
    name: 'Weighted Harness',
    detail: 'Belt-loaded leverage control for long-match carry-over.',
    focus: 'Leverage',
    xpMin: 5,
    xpMax: 10,
    xpMultiplier: 1.35,
    steroidChance: 0.18,
    hpRestore: 1,
    fatigueCost: 4,
  },
  {
    id: 'apex_lat',
    name: 'Cable Lat Press',
    detail: 'Overhead and mid-back control for high-compression resistance.',
    focus: 'Back Pressure',
    xpMin: 5,
    xpMax: 10,
    xpMultiplier: 1.34,
    steroidChance: 0.2,
    hpRestore: 2,
    fatigueCost: 5,
  },
];

export const GLORY_MACHINES: GymMachine[] = [
  {
    id: 'glory_crusher',
    name: 'Atlas Crusher',
    detail: 'Maximum overload cycles meant for late-game gym leaders.',
    focus: 'Raw Strength',
    xpMin: 6,
    xpMax: 10,
    xpMultiplier: 1.4,
    steroidChance: 0.24,
    hpRestore: 2,
    fatigueCost: 5,
  },
  {
    id: 'glory_mill',
    name: 'Spine Mill',
    detail: 'Precision endurance work to stay composed under pain.',
    focus: 'Posture',
    xpMin: 5,
    xpMax: 11,
    xpMultiplier: 1.28,
    steroidChance: 0.2,
    hpRestore: 2,
    fatigueCost: 4,
  },
  {
    id: 'glory_torso',
    name: 'Torso Matrix',
    detail: 'Machine-driven carryover for repeated clutch bursts.',
    focus: 'Core Transfer',
    xpMin: 6,
    xpMax: 12,
    xpMultiplier: 1.33,
    steroidChance: 0.23,
    hpRestore: 2,
    fatigueCost: 5,
  },
  {
    id: 'glory_deadlift',
    name: 'Monorail Deadlift Stack',
    detail: 'Boss-grade deadlift paths that punish weak stance.',
    focus: 'Ground Break',
    xpMin: 7,
    xpMax: 12,
    xpMultiplier: 1.38,
    steroidChance: 0.22,
    hpRestore: 1,
    fatigueCost: 6,
  },
];

export const ALL_TRAINING_MACHINES: GymMachine[] = [
  ...HOME_MACHINES,
  ...STARTER_A_MACHINES,
  ...STARTER_B_MACHINES,
  ...IRON_MACHINES,
  ...APEX_MACHINES,
  ...GLORY_MACHINES,
];

export const TRAINING_MACHINE_BY_ID = new Map(
  ALL_TRAINING_MACHINES.map((machine) => [machine.id, machine]),
);

export function getTrainingMachineById(id: string) {
  const machine = TRAINING_MACHINE_BY_ID.get(id);
  if (!machine) {
    throw new Error(`Unknown training machine "${id}".`);
  }
  return machine;
}
