import type { GymMachine } from '../types';

export const HOME_MACHINES: GymMachine[] = [
  {
    id: 'home_recovery',
    gymId: 'home',
    name: 'Recovery Rack',
    visualConcept: 'A low copper frame with elastic glow-bands and a slow breathing light.',
    detail: 'Teaches readiness, recovery effects, and wide timing windows.',
    focus: 'Recovery',
    primaryMuscleGroups: ['core', 'back'],
    buddyDisciplines: ['recovery', 'mobility'],
    rewardTable: {
      id: 'reward.home-recovery.completion',
      buddyXp: { min: 1, max: 3, multiplier: 0.9 },
      trainerGrowthMultiplier: 0.7,
    },
    hpEffect: 6,
    fatigueCost: 0,
    momentumEffect: 1,
    difficulty: 1,
    dropProbabilities: { boostToken: 0.01, deloadToken: 0.06 },
    recommendedTrainerLevel: { min: 1, max: 6 },
    repeatSoftCap: 2,
    animationCueId: 'machine.home-recovery.cycle',
    soundCueId: 'train',
  },
  {
    id: 'home_dumbbells',
    gymId: 'home',
    name: 'Mobility Dumbbells',
    visualConcept: 'Compact sky-blue weights orbit a marked shoulder-path rail.',
    detail: 'Teaches clean timing and trainer-to-machine alignment.',
    focus: 'Stability',
    primaryMuscleGroups: ['shoulders', 'core', 'triceps'],
    buddyDisciplines: ['technique', 'mobility'],
    rewardTable: {
      id: 'reward.home-dumbbells.completion',
      buddyXp: { min: 2, max: 4, multiplier: 1 },
      trainerGrowthMultiplier: 0.8,
    },
    hpEffect: 2,
    fatigueCost: 1,
    momentumEffect: 2,
    difficulty: 1,
    dropProbabilities: { boostToken: 0.02, deloadToken: 0.03 },
    recommendedTrainerLevel: { min: 1, max: 8 },
    repeatSoftCap: 3,
    animationCueId: 'machine.home-dumbbells.cycle',
    soundCueId: 'train',
  },
  {
    id: 'home_plate',
    gymId: 'home',
    name: 'Technique Plate Stack',
    visualConcept: 'Thin hexagonal plates rise one notch when a rep lands cleanly.',
    detail: 'Teaches load selection, form consistency, and controlled stress.',
    focus: 'Control',
    primaryMuscleGroups: ['arms', 'triceps', 'core'],
    buddyDisciplines: ['technique', 'power'],
    rewardTable: {
      id: 'reward.home-plate.completion',
      buddyXp: { min: 2, max: 5, multiplier: 1.04 },
      trainerGrowthMultiplier: 0.85,
    },
    hpEffect: 2,
    fatigueCost: 2,
    momentumEffect: 3,
    difficulty: 2,
    dropProbabilities: { boostToken: 0.025, deloadToken: 0.025 },
    recommendedTrainerLevel: { min: 2, max: 10 },
    repeatSoftCap: 3,
    animationCueId: 'machine.home-plate.cycle',
    soundCueId: 'train',
  },
  {
    id: 'home_bike',
    gymId: 'home',
    name: 'Foam Roller Bike',
    visualConcept: 'A moss-green pedal rig drives two soft recovery rollers.',
    detail: 'Teaches volume preparedness and low-risk fatigue management.',
    focus: 'Endurance',
    primaryMuscleGroups: ['quads', 'calves', 'core'],
    buddyDisciplines: ['endurance', 'recovery'],
    rewardTable: {
      id: 'reward.home-bike.completion',
      buddyXp: { min: 2, max: 4, multiplier: 1 },
      trainerGrowthMultiplier: 0.8,
    },
    hpEffect: 3,
    fatigueCost: 1,
    momentumEffect: 2,
    difficulty: 1,
    dropProbabilities: { boostToken: 0.015, deloadToken: 0.04 },
    recommendedTrainerLevel: { min: 1, max: 8 },
    repeatSoftCap: 3,
    animationCueId: 'machine.home-bike.cycle',
    soundCueId: 'train',
  },
];

export const STARTER_A_MACHINES: GymMachine[] = [
  {
    id: 'starter_a_bench',
    gymId: 'starter-a',
    name: 'Arc Bench Rack',
    visualConcept: 'A rounded amber press rail with twin safety catches and a rep beacon.',
    detail: 'Builds dependable Power while keeping risk and timing readable.',
    focus: 'Power',
    primaryMuscleGroups: ['chest', 'shoulders', 'triceps'],
    buddyDisciplines: ['power', 'endurance'],
    rewardTable: {
      id: 'reward.starter-a-bench.completion',
      buddyXp: { min: 3, max: 6, multiplier: 1.08 },
      trainerGrowthMultiplier: 0.95,
    },
    hpEffect: 0,
    fatigueCost: 3,
    momentumEffect: 2,
    difficulty: 2,
    dropProbabilities: { boostToken: 0.035, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 6, max: 16 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-a-bench.cycle',
    soundCueId: 'train',
  },
  {
    id: 'starter_a_ropes',
    gymId: 'starter-a',
    name: 'Rope Pulley Station',
    visualConcept: 'Two braided cables sweep through a luminous wrist-alignment arc.',
    detail: 'Develops repeatable grip control and forgiving reset speed.',
    focus: 'Grip',
    primaryMuscleGroups: ['arms', 'back'],
    buddyDisciplines: ['technique', 'mobility'],
    rewardTable: {
      id: 'reward.starter-a-ropes.completion',
      buddyXp: { min: 3, max: 6, multiplier: 1.06 },
      trainerGrowthMultiplier: 0.95,
    },
    hpEffect: 1,
    fatigueCost: 2,
    momentumEffect: 2,
    difficulty: 2,
    dropProbabilities: { boostToken: 0.03, deloadToken: 0.025 },
    recommendedTrainerLevel: { min: 6, max: 18 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-a-ropes.cycle',
    soundCueId: 'train',
  },
  {
    id: 'starter_a_machine',
    gymId: 'starter-a',
    name: 'Iso-Lock Cables',
    visualConcept: 'Mirrored cable arms freeze around a central lock-point crystal.',
    detail: 'Creates a dependable Technique build under moderate compression.',
    focus: 'Lockout',
    primaryMuscleGroups: ['chest', 'triceps', 'core'],
    buddyDisciplines: ['technique', 'recovery'],
    rewardTable: {
      id: 'reward.starter-a-machine.completion',
      buddyXp: { min: 3, max: 7, multiplier: 1.07 },
      trainerGrowthMultiplier: 1,
    },
    hpEffect: 0,
    fatigueCost: 3,
    momentumEffect: 2,
    difficulty: 2,
    dropProbabilities: { boostToken: 0.03, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 8, max: 18 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-a-machine.cycle',
    soundCueId: 'train',
  },
  {
    id: 'starter_a_rows',
    gymId: 'starter-a',
    name: 'Pivot Hammer Row',
    visualConcept: 'A teal flywheel drives two offset handles through a back-row path.',
    detail: 'Trades extra fatigue for dependable pulling Power and Endurance.',
    focus: 'Pull Power',
    primaryMuscleGroups: ['back', 'arms'],
    buddyDisciplines: ['power', 'endurance'],
    rewardTable: {
      id: 'reward.starter-a-rows.completion',
      buddyXp: { min: 5, max: 8, multiplier: 1.1 },
      trainerGrowthMultiplier: 1.02,
    },
    hpEffect: -1,
    fatigueCost: 4,
    momentumEffect: 2,
    difficulty: 3,
    dropProbabilities: { boostToken: 0.04, deloadToken: 0.015 },
    recommendedTrainerLevel: { min: 10, max: 20 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-a-rows.cycle',
    soundCueId: 'train',
  },
];

export const STARTER_B_MACHINES: GymMachine[] = [
  {
    id: 'starter_b_leg',
    gymId: 'starter-b',
    name: 'Slope Drive Press',
    visualConcept: 'A diagonal footplate pushes a striped power carriage uphill.',
    detail: 'Builds a stable Power and Endurance base with predictable stress.',
    focus: 'Base Drive',
    primaryMuscleGroups: ['quads', 'core'],
    buddyDisciplines: ['power', 'endurance'],
    rewardTable: {
      id: 'reward.starter-b-leg.completion',
      buddyXp: { min: 4, max: 7, multiplier: 1.1 },
      trainerGrowthMultiplier: 1.02,
    },
    hpEffect: 0,
    fatigueCost: 4,
    momentumEffect: 1,
    difficulty: 3,
    dropProbabilities: { boostToken: 0.04, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 14, max: 24 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-b-leg.cycle',
    soundCueId: 'train',
  },
  {
    id: 'starter_b_cable',
    gymId: 'starter-b',
    name: 'Tempo Selector Pulley',
    visualConcept: 'A vertical selector glides between colored tempo bands.',
    detail: 'Develops dependable Technique and Mobility through controlled acceleration.',
    focus: 'Tempo',
    primaryMuscleGroups: ['core', 'quads'],
    buddyDisciplines: ['technique', 'mobility'],
    rewardTable: {
      id: 'reward.starter-b-cable.completion',
      buddyXp: { min: 3, max: 7, multiplier: 1.08 },
      trainerGrowthMultiplier: 1,
    },
    hpEffect: 1,
    fatigueCost: 3,
    momentumEffect: 2,
    difficulty: 2,
    dropProbabilities: { boostToken: 0.035, deloadToken: 0.025 },
    recommendedTrainerLevel: { min: 14, max: 24 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-b-cable.cycle',
    soundCueId: 'train',
  },
  {
    id: 'starter_b_pulley',
    gymId: 'starter-b',
    name: 'Pulse Wall Rig',
    visualConcept: 'Wall-mounted pulleys flash in sequence toward a narrow timing latch.',
    detail: 'Rewards precise timing without demanding an extreme load.',
    focus: 'Timing',
    primaryMuscleGroups: ['core', 'shoulders', 'back'],
    buddyDisciplines: ['technique', 'mobility'],
    rewardTable: {
      id: 'reward.starter-b-pulley.completion',
      buddyXp: { min: 4, max: 7, multiplier: 1.1 },
      trainerGrowthMultiplier: 1.02,
    },
    hpEffect: 0,
    fatigueCost: 3,
    momentumEffect: 2,
    difficulty: 3,
    dropProbabilities: { boostToken: 0.04, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 16, max: 26 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-b-pulley.cycle',
    soundCueId: 'train',
  },
  {
    id: 'starter_b_leg_pulse',
    gymId: 'starter-b',
    name: 'Leg Pulse Stack',
    visualConcept: 'A broad foot sled compresses glowing springs in short rhythm bursts.',
    detail: 'Raises Endurance rewards at the cost of higher fatigue and tighter form.',
    focus: 'Endurance',
    primaryMuscleGroups: ['quads', 'calves'],
    buddyDisciplines: ['endurance', 'power'],
    rewardTable: {
      id: 'reward.starter-b-leg-pulse.completion',
      buddyXp: { min: 5, max: 8, multiplier: 1.12 },
      trainerGrowthMultiplier: 1.05,
    },
    hpEffect: -1,
    fatigueCost: 5,
    momentumEffect: 2,
    difficulty: 3,
    dropProbabilities: { boostToken: 0.045, deloadToken: 0.015 },
    recommendedTrainerLevel: { min: 18, max: 28 },
    repeatSoftCap: 4,
    animationCueId: 'machine.starter-b-leg-pulse.cycle',
    soundCueId: 'train',
  },
];

export const IRON_MACHINES: GymMachine[] = [
  {
    id: 'iron_armor',
    gymId: 'higher-1',
    name: 'Forge Cage Press',
    visualConcept: 'Dark guide rails throw orange sparks as the carriage reaches lock.',
    detail: 'Specializes Power at a clear HP and fatigue cost.',
    focus: 'Strength',
    primaryMuscleGroups: ['chest', 'back', 'arms'],
    buddyDisciplines: ['power', 'technique'],
    rewardTable: {
      id: 'reward.iron-armor.completion',
      buddyXp: { min: 6, max: 10, multiplier: 1.14 },
      trainerGrowthMultiplier: 1.1,
    },
    hpEffect: -1,
    fatigueCost: 5,
    momentumEffect: 1,
    difficulty: 4,
    dropProbabilities: { boostToken: 0.05, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 24, max: 34 },
    repeatSoftCap: 3,
    animationCueId: 'machine.iron-armor.cycle',
    soundCueId: 'train',
  },
  {
    id: 'iron_row',
    gymId: 'higher-1',
    name: 'Dynamo Hammer Row',
    visualConcept: 'A brass flywheel stores each pull and releases a cooling blue pulse.',
    detail: 'Specializes durable Endurance with moderate recovery support.',
    focus: 'Durability',
    primaryMuscleGroups: ['quads', 'calves', 'core'],
    buddyDisciplines: ['endurance', 'recovery'],
    rewardTable: {
      id: 'reward.iron-row.completion',
      buddyXp: { min: 5, max: 8, multiplier: 1.1 },
      trainerGrowthMultiplier: 1.06,
    },
    hpEffect: 0,
    fatigueCost: 4,
    momentumEffect: 1,
    difficulty: 3,
    dropProbabilities: { boostToken: 0.045, deloadToken: 0.03 },
    recommendedTrainerLevel: { min: 24, max: 34 },
    repeatSoftCap: 3,
    animationCueId: 'machine.iron-row.cycle',
    soundCueId: 'train',
  },
  {
    id: 'iron_chain',
    gymId: 'higher-1',
    name: 'Chain Arc Stack',
    visualConcept: 'Linked counterweights rattle through an uneven resistance curve.',
    detail: 'Specializes explosive lockout Technique with meaningful failure risk.',
    focus: 'Lockout',
    primaryMuscleGroups: ['chest', 'triceps', 'core'],
    buddyDisciplines: ['technique', 'power'],
    rewardTable: {
      id: 'reward.iron-chain.completion',
      buddyXp: { min: 6, max: 9, multiplier: 1.13 },
      trainerGrowthMultiplier: 1.1,
    },
    hpEffect: -1,
    fatigueCost: 5,
    momentumEffect: 1,
    difficulty: 4,
    dropProbabilities: { boostToken: 0.055, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 26, max: 36 },
    repeatSoftCap: 3,
    animationCueId: 'machine.iron-chain.cycle',
    soundCueId: 'train',
  },
  {
    id: 'iron_grip',
    gymId: 'higher-1',
    name: 'Wide-Grip Tower',
    visualConcept: 'Oversized rotating handles climb a narrow iron column.',
    detail: 'Specializes late-set control while taxing HP and fatigue.',
    focus: 'Grip',
    primaryMuscleGroups: ['arms', 'back'],
    buddyDisciplines: ['technique', 'endurance'],
    rewardTable: {
      id: 'reward.iron-grip.completion',
      buddyXp: { min: 5, max: 9, multiplier: 1.12 },
      trainerGrowthMultiplier: 1.12,
    },
    hpEffect: -1,
    fatigueCost: 4,
    momentumEffect: 2,
    difficulty: 4,
    dropProbabilities: { boostToken: 0.055, deloadToken: 0.015 },
    recommendedTrainerLevel: { min: 27, max: 36 },
    repeatSoftCap: 3,
    animationCueId: 'machine.iron-grip.cycle',
    soundCueId: 'train',
  },
];

export const APEX_MACHINES: GymMachine[] = [
  {
    id: 'apex_platform',
    gymId: 'higher-2',
    name: 'Microload Squeeze Press',
    visualConcept: 'Floating violet plates align to a single bright precision seam.',
    detail: 'High-risk Technique specialization with strong clean-set rewards.',
    focus: 'Precision',
    primaryMuscleGroups: ['triceps', 'shoulders', 'core'],
    buddyDisciplines: ['technique', 'power'],
    rewardTable: {
      id: 'reward.apex-platform.completion',
      buddyXp: { min: 6, max: 10, multiplier: 1.16 },
      trainerGrowthMultiplier: 1.18,
    },
    hpEffect: -2,
    fatigueCost: 6,
    momentumEffect: 0,
    difficulty: 4,
    dropProbabilities: { boostToken: 0.065, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 34, max: 44 },
    repeatSoftCap: 3,
    animationCueId: 'machine.apex-platform.cycle',
    soundCueId: 'train',
  },
  {
    id: 'apex_blink',
    gymId: 'higher-2',
    name: 'Blink Row Matrix',
    visualConcept: 'Three offset handles light in a looping cyan rhythm pattern.',
    detail: 'Specializes Mobility and Endurance through demanding rhythm changes.',
    focus: 'Rhythm',
    primaryMuscleGroups: ['core', 'calves'],
    buddyDisciplines: ['mobility', 'endurance'],
    rewardTable: {
      id: 'reward.apex-blink.completion',
      buddyXp: { min: 5, max: 9, multiplier: 1.13 },
      trainerGrowthMultiplier: 1.12,
    },
    hpEffect: -1,
    fatigueCost: 5,
    momentumEffect: 2,
    difficulty: 4,
    dropProbabilities: { boostToken: 0.055, deloadToken: 0.03 },
    recommendedTrainerLevel: { min: 34, max: 44 },
    repeatSoftCap: 3,
    animationCueId: 'machine.apex-blink.cycle',
    soundCueId: 'train',
  },
  {
    id: 'apex_harness',
    gymId: 'higher-2',
    name: 'Vector Harness',
    visualConcept: 'A suspended belt pulls against four directional leverage anchors.',
    detail: 'High-value leverage specialization with severe load pressure.',
    focus: 'Leverage',
    primaryMuscleGroups: ['back', 'chest', 'core'],
    buddyDisciplines: ['technique', 'power'],
    rewardTable: {
      id: 'reward.apex-harness.completion',
      buddyXp: { min: 7, max: 11, multiplier: 1.18 },
      trainerGrowthMultiplier: 1.2,
    },
    hpEffect: -2,
    fatigueCost: 6,
    momentumEffect: 0,
    difficulty: 5,
    dropProbabilities: { boostToken: 0.07, deloadToken: 0.015 },
    recommendedTrainerLevel: { min: 36, max: 46 },
    repeatSoftCap: 3,
    animationCueId: 'machine.apex-harness.cycle',
    soundCueId: 'train',
  },
  {
    id: 'apex_lat',
    gymId: 'higher-2',
    name: 'Compression Lat Press',
    visualConcept: 'Overhead fins fold toward a deep-blue pressure core.',
    detail: 'Specializes back pressure with a small Recovery crossover.',
    focus: 'Back Pressure',
    primaryMuscleGroups: ['back', 'core'],
    buddyDisciplines: ['power', 'recovery'],
    rewardTable: {
      id: 'reward.apex-lat.completion',
      buddyXp: { min: 6, max: 10, multiplier: 1.16 },
      trainerGrowthMultiplier: 1.17,
    },
    hpEffect: -2,
    fatigueCost: 6,
    momentumEffect: 1,
    difficulty: 4,
    dropProbabilities: { boostToken: 0.06, deloadToken: 0.025 },
    recommendedTrainerLevel: { min: 36, max: 46 },
    repeatSoftCap: 3,
    animationCueId: 'machine.apex-lat.cycle',
    soundCueId: 'train',
  },
];

export const GLORY_MACHINES: GymMachine[] = [
  {
    id: 'glory_crusher',
    gymId: 'higher-3',
    name: 'Crown Crusher',
    visualConcept: 'A gold-and-crimson press closes beneath a floating crown gauge.',
    detail: 'Extreme Power specialization with high HP, fatigue, and timing risk.',
    focus: 'Raw Strength',
    primaryMuscleGroups: ['chest', 'arms'],
    buddyDisciplines: ['power'],
    rewardTable: {
      id: 'reward.glory-crusher.completion',
      buddyXp: { min: 9, max: 13, multiplier: 1.2 },
      trainerGrowthMultiplier: 1.28,
    },
    hpEffect: -3,
    fatigueCost: 7,
    momentumEffect: 0,
    difficulty: 5,
    dropProbabilities: { boostToken: 0.075, deloadToken: 0.015 },
    recommendedTrainerLevel: { min: 44, max: 55 },
    repeatSoftCap: 2,
    animationCueId: 'machine.glory-crusher.cycle',
    soundCueId: 'train',
  },
  {
    id: 'glory_mill',
    gymId: 'higher-3',
    name: 'Composure Mill',
    visualConcept: 'A silver posture wheel turns through alternating balance gates.',
    detail: 'Endgame Technique and Endurance specialization that rewards composure.',
    focus: 'Posture',
    primaryMuscleGroups: ['shoulders', 'core'],
    buddyDisciplines: ['technique', 'endurance'],
    rewardTable: {
      id: 'reward.glory-mill.completion',
      buddyXp: { min: 7, max: 11, multiplier: 1.16 },
      trainerGrowthMultiplier: 1.22,
    },
    hpEffect: -1,
    fatigueCost: 6,
    momentumEffect: 2,
    difficulty: 4,
    dropProbabilities: { boostToken: 0.065, deloadToken: 0.03 },
    recommendedTrainerLevel: { min: 42, max: 55 },
    repeatSoftCap: 3,
    animationCueId: 'machine.glory-mill.cycle',
    soundCueId: 'train',
  },
  {
    id: 'glory_torso',
    gymId: 'higher-3',
    name: 'Torso Relay Matrix',
    visualConcept: 'Four linked pads pass a bright impulse around a central core ring.',
    detail: 'Endgame transfer specialization balancing Power and Mobility.',
    focus: 'Core Transfer',
    primaryMuscleGroups: ['core', 'quads'],
    buddyDisciplines: ['power', 'mobility'],
    rewardTable: {
      id: 'reward.glory-torso.completion',
      buddyXp: { min: 8, max: 12, multiplier: 1.18 },
      trainerGrowthMultiplier: 1.24,
    },
    hpEffect: -2,
    fatigueCost: 7,
    momentumEffect: 1,
    difficulty: 5,
    dropProbabilities: { boostToken: 0.07, deloadToken: 0.02 },
    recommendedTrainerLevel: { min: 44, max: 55 },
    repeatSoftCap: 3,
    animationCueId: 'machine.glory-torso.cycle',
    soundCueId: 'train',
  },
  {
    id: 'glory_deadlift',
    gymId: 'higher-3',
    name: 'Monorail Ground Stack',
    visualConcept: 'A black floor carriage breaks free along a single glowing rail.',
    detail: 'Highest raw XP potential with the roster’s greatest fatigue and HP cost.',
    focus: 'Ground Break',
    primaryMuscleGroups: ['quads', 'calves', 'core', 'back'],
    buddyDisciplines: ['power', 'endurance'],
    rewardTable: {
      id: 'reward.glory-deadlift.completion',
      buddyXp: { min: 10, max: 14, multiplier: 1.2 },
      trainerGrowthMultiplier: 1.3,
    },
    hpEffect: -4,
    fatigueCost: 8,
    momentumEffect: -1,
    difficulty: 5,
    dropProbabilities: { boostToken: 0.08, deloadToken: 0.01 },
    recommendedTrainerLevel: { min: 46, max: 55 },
    repeatSoftCap: 2,
    animationCueId: 'machine.glory-deadlift.cycle',
    soundCueId: 'train',
  },
];

export const ALL_TRAINING_MACHINES: GymMachine[] = [
  ...HOME_MACHINES,
  ...STARTER_A_MACHINES,
  ...STARTER_B_MACHINES,
  ...IRON_MACHINES,
  ...APEX_MACHINES,
  ...GLORY_MACHINES,
];

export const TRAINING_MACHINE_BY_ID = new Map(
  ALL_TRAINING_MACHINES.map((machine) => [machine.id, machine]),
);

export function getTrainingMachineById(id: string) {
  const machine = TRAINING_MACHINE_BY_ID.get(id);
  if (!machine) {
    throw new Error(`Unknown training machine "${id}".`);
  }
  return machine;
}
